### ISSUE TITLE
[ERROR] AttributeError: 'Searches' object has no attribute 'bingSearchesWithScrolling'

### ISSUE THREAD

**Issue by darkimage404** [klept0/MS-Rewards-Farmer#12]
2023-10-26 12:46:00,623 [ERROR] AttributeError: 'Searches' object has no attribute 'bingSearchesWithScrolling'
Traceback (most recent call last):
  File "/Users/simone/Downloads/MS-Rewards-Farmer-master/main.py", line 39, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/simone/Downloads/MS-Rewards-Farmer-master/main.py", line 200, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearchesWithScrolling(
                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'Searches' object has no attribute 'bingSearchesWithScrolling'
Points data saved for the next day.

**Comment by klept0** [comment]
I reverted the changes - I will revisit this at a later time
