### ISSUE TITLE
[BUG] Typo In Code Solved With ChatGpt json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5

### ISSUE THREAD

**Issue by nitay100** [klept0/MS-Rewards-Farmer#128]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

the bug happend because the accounts.json file have a , after the quotes on 4 line can be fixed by removing it

### Copy and paste your error

C:\Users\nitay\Downloads\MS-Rewards-Farmer-master>python main.py
Traceback (most recent call last):
File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 316, in
main()
File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 33, in main
loadedAccounts = setupAccounts()
^^^^^^^^^^^^^^^
File "C:\Users\nitay\Downloads\MS-Rewards-Farmer-master\main.py", line 179, in setupAccounts
loadedAccounts = json.loads(accountPath.read_text(encoding="utf-8"))
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json_init_.py", line 346, in loads
return _default_decoder.decode(s)
^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 337, in decode
obj, end = self.raw_decode(s, idx=_w(s, 0).end())
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "C:\Users\nitay\AppData\Local\Programs\Python\Python311\Lib\json\decoder.py", line 353, in raw_decode
obj, end = self.scan_once(s, idx)
^^^^^^^^^^^^^^^^^^^^^^
json.decoder.JSONDecodeError: Expecting property name enclosed in double quotes: line 5 column 5 (char 90)

### Screenshots

idk

### Value of dashboard variable

idk

**Comment by Titaniumtown** [comment]
Solved with chatgpt? what?

**Comment by xnuit** [comment]
I had the same problem, it indeed happens when you forget to remove the comma on the last line after removing the proxy line in the accounts.json file

**Comment by cal4** [comment]
Closing, indeed looks like misformatted accounts.json.
