### ISSUE TITLE
[BUG] Failed at mobile searches?

### ISSUE THREAD

**Issue by SteveeeeeS** [klept0/MS-Rewards-Farmer#143]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

142?

### Describe the bug

seems to always fail after bing edge searches and exits.

### Copy and paste your error

2024-07-09 16:03:38,644 [WARNING] [BING] Possible blockage. Refreshing the page.
2024-07-09 16:03:40,448 [INFO] [BING] Finished Desktop Edge Bing searches !

DevTools listening on ws://127.0.0.1:61392/devtools/browser/b97b0602-0159-4b56-8688-2f44f6316022
Traceback (most recent call last):
  File "C:\Users\steph\GitHub\MS-Rewards-Farmer\main.py", line 43, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\GitHub\MS-Rewards-Farmer\main.py", line 245, in executeBot
    with Browser(mobile=True, account=currentAccount, args=args) as mobileBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Screenshots

2024-07-09 16:03:38,644 [WARNING] [BING] Possible blockage. Refreshing the page.
2024-07-09 16:03:40,448 [INFO] [BING] Finished Desktop Edge Bing searches !

DevTools listening on ws://127.0.0.1:61392/devtools/browser/b97b0602-0159-4b56-8688-2f44f6316022
Traceback (most recent call last):
  File "C:\Users\steph\GitHub\MS-Rewards-Farmer\main.py", line 43, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\GitHub\MS-Rewards-Farmer\main.py", line 245, in executeBot
    with Browser(mobile=True, account=currentAccount, args=args) as mobileBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

### Value of dashboard variable

na

**Comment by cal4** [comment]
Give develop a shot, see if that fixes your issue

**Comment by klept0** [comment]
Check to see if the new release resolves your issue
