### ISSUE TITLE
No websearch :(

### ISSUE THREAD

**Issue by GrrGrrMan** [klept0/MS-Rewards-Farmer#145]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

???

### Describe the bug

After ..completing more premotions successful it will send a Devtool listen again and error:

### Copy and paste your error

←[38;5;39m2024-07-10 18:23:04,716 [INFO] [MORE PROMOS] Completed More Promotions successfully !←[0m

DevTools listening on ws://127.0.0.1:53478/devtools/browser/84054cba-a95b-4b2f-9a7e-d3e5f36cb37b
←[38;5;39m2024-07-10 18:24:53,073 [INFO] Sent Discord notification.←[0m
←[38;5;196m2024-07-10 18:24:53,179 [ERROR] SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:53503
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x003CC1C3+27395]
        (No symbol) [0x00363DC4]
        (No symbol) [0x002619FD]
        (No symbol) [0x002503AC]
        (No symbol) [0x00293D22]
        (No symbol) [0x0028AD50]
        (No symbol) [0x0028AB97]
        (No symbol) [0x002CD58E]
        (No symbol) [0x002CCDAA]
        (No symbol) [0x002C3736]
        (No symbol) [0x00297541]
        (No symbol) [0x002980BD]
        GetHandleVerifier [0x00683A93+2876371]
        GetHandleVerifier [0x006D7F5D+3221661]
        GetHandleVerifier [0x0044D634+556916]
        GetHandleVerifier [0x0045474C+585868]
        (No symbol) [0x0036CE04]
        (No symbol) [0x00369818]
        (No symbol) [0x003699B7]
        (No symbol) [0x0035BF0E]
        BaseThreadInitThunk [0x75F2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77B980CE+286]
        RtlGetAppContainerNamedObjectPath [0x77B9809E+238]
←[0m
Traceback (most recent call last):
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\main.py", line 43, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\main.py", line 245, in executeBot
    with Browser(mobile=True, account=currentAccount, args=args) as mobileBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\src\browser.py", line 42, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\src\browser.py", line 92, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:53503
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x003CC1C3+27395]
        (No symbol) [0x00363DC4]
        (No symbol) [0x002619FD]
        (No symbol) [0x002503AC]
        (No symbol) [0x00293D22]
        (No symbol) [0x0028AD50]
        (No symbol) [0x0028AB97]
        (No symbol) [0x002CD58E]
        (No symbol) [0x002CCDAA]
        (No symbol) [0x002C3736]
        (No symbol) [0x00297541]
        (No symbol) [0x002980BD]
        GetHandleVerifier [0x00683A93+2876371]
        GetHandleVerifier [0x006D7F5D+3221661]
        GetHandleVerifier [0x0044D634+556916]
        GetHandleVerifier [0x0045474C+585868]
        (No symbol) [0x0036CE04]
        (No symbol) [0x00369818]
        (No symbol) [0x003699B7]
        (No symbol) [0x0035BF0E]
        BaseThreadInitThunk [0x75F2FCC9+25]
        RtlGetAppContainerNamedObjectPath [0x77B980CE+286]
        RtlGetAppContainerNamedObjectPath [0x77B9809E+238]

←[38;5;39m2024-07-10 18:24:54,094 [INFO] ********************aaliyahaldrich@outlook.com********************←[0m

DevTools listening on ws://127.0.0.1:53634/devtools/browser/fb6f1293-b111-4b60-bea9-e61804f273bc
Exception ignored when trying to send to the signal wakeup fd:
Traceback (most recent call last):
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1013, in close
    def close(self):

OSError: [WinError 10038] An operation was attempted on something that is not a socket
Exception ignored when trying to send to the signal wakeup fd:
Traceback (most recent call last):
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1013, in close
    def close(self):

OSError: [WinError 10038] An operation was attempted on something that is not a socket
Exception ignored in: <function Service.__del__ at 0x0000011E428FCCC0>
Traceback (most recent call last):
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 189, in __del__
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 146, in stop
Exception ignored when trying to send to the signal wakeup fd:
Traceback (most recent call last):
  File "<frozen codecs>", line 309, in __init__
OSError: [WinError 10038] An operation was attempted on something that is not a socket
    self.send_remote_shutdown_command()
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\common\service.py", line 126, in send_remote_shutdown_command
    request.urlopen(f"{self.service_url}/shutdown")
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1373, in http_open
    return self.do_open(http.client.HTTPConnection, req)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1001, in connect
    self.sock = self._create_connection(
                ^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 845, in create_connection
KeyboardInterrupt:
Exception ignored when trying to send to the signal wakeup fd:
Traceback (most recent call last):
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\socket.py", line 244, in __repr__
    def __repr__(self):

OSError: [WinError 10038] An operation was attempted on something that is not a socket
Traceback (most recent call last):
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\main.py", line 318, in <module>
    main()
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\main.py", line 43, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\main.py", line 199, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\src\browser.py", line 42, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\Downloads\MS-Rewards-Farmer-master\src\browser.py", line 92, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 258, in __init__
    self.patcher.auto()
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 178, in auto
    self.unzip_package(self.fetch_package())
                       ^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\patcher.py", line 287, in fetch_package
    return urlretrieve(download_url)[0]
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 240, in urlretrieve
    with contextlib.closing(urlopen(url, data)) as fp:
                            ^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 215, in urlopen
    return opener.open(url, data, timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 515, in open
    response = self._open(req, data)
               ^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 532, in _open
    result = self._call_chain(self.handle_open, protocol, protocol +
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 492, in _call_chain
    result = func(*args)
             ^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1392, in https_open
    return self.do_open(http.client.HTTPSConnection, req,
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\urllib\request.py", line 1344, in do_open
    h.request(req.get_method(), req.selector, req.data, headers,
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1336, in request
    self._send_request(method, url, body, headers, encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1382, in _send_request
    self.endheaders(body, encode_chunked=encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1331, in endheaders
    self._send_output(message_body, encode_chunked=encode_chunked)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1091, in _send_output
    self.send(msg)
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1035, in send
    self.connect()
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\http\client.py", line 1477, in connect
    self.sock = self._context.wrap_socket(self.sock,
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 455, in wrap_socket
    return self.sslsocket_class._create(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1042, in _create
    self.do_handshake()
  File "C:\Users\jiuma\AppData\Local\Programs\Python\Python312\Lib\ssl.py", line 1320, in do_handshake
    self._sslobj.do_handshake()
KeyboardInterrupt

### Screenshots

![image](https://github.com/klept0/MS-Rewards-Farmer/assets/172151455/ece1eba8-e915-47a3-a2e6-ab47d4341c35)

### Value of dashboard variable

            MeePortal.Rewards.Clarity.clarityInit(window, document, "clarity", "script", "76hfh21kdi");
            var dashboard = {"userStatus":{"levelInfo":{"activeLevel":"Level2","activeLevelName":"Level 2","progress":669,"progressMax":500,"levels":[{"key":"Level1","active":false,"name":"Level 1","tasks":[{"text":"Free and included with your Microsoft account","url":null}],"privileges":[{"text":"1 point per $1 spent in Microsoft Store, plus earn bonus points on select purchases","url":"//www.microsoftstore.com"},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts","url":null},{"text":"Redeem your points for gift cards, sweepstakes entries, or donate them to charity","url":"/rewards/redeem"}]},{"key":"Level2","active":true,"name":"Level 2","tasks":[{"text":"Earn at least 500 points each month","url":null}],"privileges":[{"text":"Level 1 Microsoft Store benefits, plus exclusive Level 2 bonus offers","url":null},{"text":"Points for exploring offers from Microsoft Rewards","url":"/rewards/dashboard"},{"text":"Access to member sales and discounts, with exclusives for Level 2 members","url":null},{"text":"Get up to 10% off when redeeming rewards from Microsoft brands","url":null}]}],"benefitsPromotion":{"benefits":[{"key":"BingSearch","text":"Daily Bing search point limit (3 points per search)*","url":"https://www.bing.com/?FORM=MA1368","helpText":"* The Level 2 Bing search benefit is the sum of 90 points on PC and 60 points on mobile","supportedLevels":{"level1":"30","level2":"150","level2XBoxGold":"150"}},{"key":"PointsDollarSpent","text":"Points earned per $ spent in Microsoft Store online**","url":"https://www.microsoft.com/store/b/home?rtc=1","helpText":"**Qualifying content only. \u003ca class=\u0027c-hyperlink\u0027 href=\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\u0027\u003eSee more\u003c/a\u003e for details.","supportedLevels":{"level1":"1:1","level2":"10:1","level2XBoxGold":"20:1"}},{"key":"PointsSeeDailyOffers","text":"Points for exploring daily offers","url":"https://account.microsoft.com/rewards","helpText":null,"supportedLevels":{"level1":"","level2":"","level2XBoxGold":""}},{"key":"MemberDiscounts","text":"Access to exclusive member sales and discounts","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"MemberInvites","text":"Occasional surprise invites to exclusive member-only events","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}},{"key":"RedeemOff","text":"Up to 10% off when redeeming from Microsoft brands","url":null,"helpText":null,"supportedLevels":{"level2":"","level2XBoxGold":""}}],"supportedLevelKeys":["level1","level2","level2XBoxGold"],"supportedLevelTitles":["Level 1","Level 2","Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Game Pass Ultimate\u003c/span\u003e"],"supportedLevelTitlesMobile":["Level 1","Level 2","Level 2 +Xbox Game Pass Ultimate"],"activeLevel":"level2","name":"level_benefits","priority":1,"attributes":{"activeLevel":"level2","benefits":"[{ key: \u0027BingSearch\u0027, text: \u0027Daily Bing search point limit (3 points per search)*\u0027, url: \u0027https://www.bing.com/?FORM=MA1368\u0027, helpText: \u0027* The Level 2 Bing search benefit is the sum of 90 points on PC and 60 points on mobile\u0027, supportedLevels: { \u0027level1\u0027: \u002730\u0027, \u0027level2\u0027: \u0027150\u0027, level2XBoxGold: \u0027150\u0027 } }, { key: \u0027PointsDollarSpent\u0027, text: \u0027Points earned per $ spent in Microsoft Store online**\u0027, url: \u0027https://www.microsoft.com/store/b/home?rtc=1\u0027, helpText: \u0027**Qualifying content only. \u003ca class=\\\u0027c-hyperlink\\\u0027 href=\\\u0027https://www.microsoft.com/rewards/xbox/transition-overview?form=ML18S9\u0026OCID=ML18S9\u0026rtc=1\\\u0027\u003eSee more\u003c/a\u003e for details.\u0027, supportedLevels: { \u0027level1\u0027: \u00271:1\u0027, \u0027level2\u0027: \u002710:1\u0027, level2XBoxGold: \u002720:1\u0027 } }, { key: \u0027PointsSeeDailyOffers\u0027, text: \u0027Points for exploring daily offers\u0027, url: \u0027https://account.microsoft.com/rewards\u0027, supportedLevels: { \u0027level1\u0027: \u0027\u0027, \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 } }, { key: \u0027MemberDiscounts\u0027, text: \u0027Access to exclusive member sales and discounts\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }  }, { key: \u0027MemberInvites\u0027, text: \u0027Occasional surprise invites to exclusive member-only events\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}, { key: \u0027RedeemOff\u0027, text: \u0027Up to 10% off when redeeming from Microsoft brands\u0027, supportedLevels: { \u0027level2\u0027: \u0027\u0027, level2XBoxGold: \u0027\u0027 }}]","hidden":"True","levelTitleMobile":"Level 1;Level 2;Level 2 +Xbox Game Pass Ultimate","supportedLevelKeys":"level1;level2;level2XBoxGold","supportedLevelTitle":"Level 1;Level 2;Level 2\u003cbr/\u003e\u003cspan class=\u0027highlightGold\u0027\u003e+Xbox Game Pass Ultimate\u003c/span\u003e","give_eligible":"False","destination":""},"offerId":"","complete":false,"counter":0,"activityProgress":0,"activityProgressMax":0,"pointProgressMax":0,"pointProgress":0,"promotionType":"","promotionSubtype":"","title":"","extBannerTitle":"","titleStyle":"","theme":"","description":"","extBannerDescription":"","descriptionStyle":"","showcaseTitle":"","showcaseDescription":"","imageUrl":"","dynamicImage":"","smallImageUrl":"","backgroundImageUrl":"","showcaseBackgroundImageUrl":"","showcaseBackgroundLargeImageUrl":"","promotionBackgroundLeft":"","promotionBackgroundRight":"","iconUrl":"","animatedIconUrl":"","animatedLargeBackgroundImageUrl":"","destinationUrl":"","linkText":"","hash":"53b28ef7f02a15ccbb5b13e737b1ea7b4998ba9b611090e43e25a4e5f224c0da","activityType":"11","isRecurring":false,"isHidden":true,"isTestOnly":false,"isGiveEligible":false,"level":"","slidesCount":0,"legalText":"","legalLinkText":"","deviceType":"","exclusiveLockedFeatureType":"notsupported","exclusiveLockedFeatureStatus":"notsupported"}},"availablePoints":719,"lifetimePoints":719,"lifetimePointsRedeemed":0,"migratedGiveBalance":0,"ePuid":"G2Ndxq12oWSbtWx2JJpbagTAxRJxoTRVymKKw3Fy4dzTZRDFpENCpjW-XclTnHHHRBCy9Zs_IA__uYtm9LDNLnCX4a7nbTLKskVS6UMPKq8","redeemGoal":{"name":"000407000065","price":1500,"provider":"tango","disabled":false,"category":"Shop","title":"Roblox Digital Card—100 Robux","variableGoalSpecificTitle":"","smallImageUrl":"small/000400000343_v1_142x142.png","mediumImageUrl":"medium/000400000343_v3_262x164.png","largeImageUrl":"large/000400000343_v1_310x216.png","largeShowcaseImageUrl":"showcasev2/000400000343_v1_644x360.png","description":{"itemGroupText":"100 Robux","smallText":"","largeText":"\u003cdiv class=\u0022prizeText\u0022\u003e\r\n\u003cp\u003eRoblox is the ultimate virtual universe that lets you connect, create, share experiences with friends, and be anything you can imagine. Join millions of people and discover an infinite variety of immersive 3D experiences created by a global community!\u003c/p\u003e\r\n\u003cp class=\u0022paddingtop10\u0022\u003eGet new accessories, emotes, and more for your avatar!\u003c/p\u003e\r\n\u003cp class=\u0022paddingtop10\u0022\u003e\u003cb\u003eRoblox Digital Card Terms and Conditions\u003c/b\u003e\u003c/p\u003e\r\n\u003cp class=\u0022SmallFont paddingtop10\u0022\u003eThis card may only be redeemed at \u003ca href=\u0022https://www.roblox.com/\u0022 rel=\u0022noopener noreferrer\u0022 target=\u0022_blank\u0022\u003ewww.roblox.com\u003c/a\u003e for Robux, which may only be used to obtain certain products and services at www.roblox.com. Availability and pricing of products and services is subject to change and age restrictions may apply. To redeem this card and use Robux, you must have Internet access, register for a Roblox account and accept the Roblox Terms of Use. No partial redemption is permitted. This card is not redeemable for cash or credit, except as and where required by law. Resale is strictly prohibited. Roblox is not responsible if this card is used without your permission or if it is lost, stolen or forgotten. A card obtained by fraud will not be honoured. Only one virtual item is made available per account per month or such other period as Roblox may designate. For minimum system requirements and more information, please visit \u003ca href=\u0022https://www.roblox.com/\u0022 rel=\u0022noopener noreferrer\u0022 target=\u0022_blank\u0022\u003ewww.roblox.com\u003c/a\u003e or contact us at \u003ca href=\u0022https://www.roblox.com/support\u0022 rel=\u0022noopener noreferrer\u0022 target=\u0022_blank\u0022\u003ewww.roblox.com/support\u003c/a\u003e.\u003c/p\u003e\r\n\u003c/div\u003e","legalText":"","showcaseTitle":"Imagine, create and play together","showcaseDescription":"Redeem for Robux and get new accessories, emotes, and more for your Roblox avatar!","pageTitleTag":"","metaDescription":""},"showcase":false,"showcaseInAllCategory":false,"originalPrice":1500,"discountedPrice":1500,"couponDiscount":0,"popular":false,"isTestOnly":false,"groupId":"000407000065","inGroup":true,"isDefaultItemInGroup":true,"groupTitle":"Roblox Digital Card","groupImageUrl":"medium/000400000343_v3_262x164.png","groupShowcaseImageUrl":"showcasev2/000400000343_v1_644x360.png","isEligibleForOneClickRedemption":false,"instantWinGameId":"","instantWinPlayAgainSku":"","isLowInStock":false,"isOutOfStock":false,"getCodeMessage":"","disableEmail":false,"stockMessage":"","comingSoonFlag":false,"isGenericDonation":false,"shouldDisableButton":false,"isVariableRedemptionItem":false,"variableRedemptionItemCurrencySymbol":null,"variableRedemptionItemMin":0,"variableRedemptionItemMax":0,"variableItemConfigPointsToCurrencyConversionRatio":0.0,"isRecommen…

**Comment by cal4** [comment]
Does this happen every run?

**Comment by rakosi2** [comment]
Also happening to me every run since yesterday

**Comment by cal4** [comment]
I'd recommend checking out the develop branch and running to see if it fixes the issue

**Comment by rakosi2** [comment]
> I'd recommend checking out the develop branch and running to see if it fixes the issue

appears to be an issue there too, made sure to run `pip install --upgrade` too
![image](https://github.com/klept0/MS-Rewards-Farmer/assets/6037087/30c208fd-4392-4acb-994b-1e55466686d6)

**Comment by cal4** [comment]
Are there any leftover Chrome processes? Make a note if you do, kill em and re-run. It looks like a previous run didn't clean them up properly and they're still hanging around bound to needed ports.

**Comment by SteveeeeeS** [comment]
I get this AOT, and yes i believe chrome processes stay open..

**Comment by rakosi2** [comment]
deleted the sessions folder and still errors, no chrome process running
[error.log](https://github.com/user-attachments/files/16169288/error.log)

**Comment by cal4** [comment]
@rakosi2 Looks like a separate issue, but searches are getting done

**Comment by rakosi2** [comment]
sorry about that I guess, looked similar to me.

**Comment by cal4** [comment]
That being said, looks like there's some problems with promos in the log you shared

**Comment by thgilciffart** [comment]
I'm getting this error as well on macos
