### ISSUE TITLE
google trends is empty

### ISSUE THREAD

**Issue by M1r0zo** [klept0/MS-Rewards-Farmer#162]
```
2024-08-03 16:09:35,590 [DEBUG] googleTrendsShelf.__dict__ = {'dict': <dbm.dumb._Database object at 0x000001E50D155330>, '_protocol': 4, 'writeback': False, 'cache': {}, 'keyencoding': 'utf-8'}
2024-08-03 16:09:35,590 [DEBUG] google_trends = []
2024-08-03 16:09:52,590 [DEBUG] in __exit__ exc_type=<class 'AssertionError'> exc_value= traceback=<traceback object at 0x000001E50AF58680>
2024-08-03 16:09:53,004 [ERROR]
Traceback (most recent call last):
  File "C:\MS-Rewards-Farmer\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
  File "C:\MS-Rewards-Farmer\main.py", line 247, in executeBot
    with Searches(desktopBrowser) as searches:
  File "C:\MS-Rewards-Farmer\src\searches.py", line 72, in __init__
    trends = self.getGoogleTrends(
  File "C:\Downloads\MS-Rewards-Farmer\src\searches.py", line 100, in getGoogleTrends
    assert r.status_code == requests.codes.ok
AssertionError
2024-08-03 16:09:53,676 [INFO] [POINTS] Data saved for the next day.
```

**Comment by cal4** [comment]
That AssertionError indicates your bot isn't reaching trends.google.com successfully. Try running again, and if it continues to be a problem you'll want to adjust the retry config in src.utils.Utils.makeRequestsSession for your environment.

**Comment by cal4** [comment]
Feel free to reopen if needed
