### ISSUE TITLE
[BUG] blinker package not found

### ISSUE THREAD

**Issue by he-sb** [klept0/MS-Rewards-Farmer#167]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

35f808b

### Describe the bug

after [this](https://github.com/klept0/MS-Rewards-Farmer/commit/35f808bcd0ab977345a4bd1ba55932759e4350fc) commit, I got error:

```
ModuleNotFoundError: No module named 'blinker._saferef'
```

### Copy and paste your error

```
Traceback (most recent call last):
  File "/app/main.py", line 13, in <module>
    from src import (
  File "/app/src/__init__.py", line 2, in <module>
    from .browser import Browser
  File "/app/src/browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/inspect.py", line 7, in <module>
    from seleniumwire import har
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/net/tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "/usr/local/lib/python3.12/site-packages/seleniumwire/thirdparty/mitmproxy/optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'
```

### Screenshots

irrelevant

### Value of dashboard variable

irrelevant

**Comment by klept0** [comment]
I unpinned the version accidentally - check it with the pinned version and it should be resolved for now.
