### ISSUE TITLE
</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>

### ISSUE THREAD

**Issue by SteveeeeeS** [klept0/MS-Rewards-Farmer#169]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

??

### Describe the bug

bing searches failing. tried a release from last week and different machnes. Maybe the webpage has change positions?
</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>

### Copy and paste your error

2024-08-08 14:43:18,523 [DEBUG] terms=['riots in uk today', 'riots in uk', 'riots in london today update', 'riots games', 'riotgames.com login', 'riots in leeds', 'riots', 'rioty-select', 'riotlol kick', 'riotravel', 'riotclientservices exe', 'riotous meaning']
2024-08-08 14:43:18,523 [DEBUG] rootTerm=riot
2024-08-08 14:43:19,635 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.ElementClickInterceptedException'> exc_value=Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">vienna blood</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
        GetHandleVerifier [0x00428923+23283]
        (No symbol) [0x003EE934]
        (No symbol) [0x00320733]
        (No symbol) [0x003691C7]
        (No symbol) [0x003675D9]
        (No symbol) [0x003654CB]
        (No symbol) [0x00364AAF]
        (No symbol) [0x003599EF]
        (No symbol) [0x0038441C]
        (No symbol) [0x00359485]
        (No symbol) [0x003846B4]
        (No symbol) [0x0039CB8D]
        (No symbol) [0x003841B6]
        (No symbol) [0x00358017]
        (No symbol) [0x0035890D]
        GetHandleVerifier [0x0051A5E3+1013683]
        GetHandleVerifier [0x00523E3C+1052684]
        GetHandleVerifier [0x0051D4A4+1025652]
        GetHandleVerifier [0x0044EA2B+179195]
        (No symbol) [0x003F6833]
        (No symbol) [0x003F3198]
        (No symbol) [0x003F3337]
        (No symbol) [0x003EB4BE]
        BaseThreadInitThunk [0x76617BA9+25]
        RtlInitializeExceptionChain [0x7714C10B+107]
        RtlClearBits [0x7714C08F+191]
 traceback=<traceback object at 0x000002C4B3410800>
2024-08-08 14:43:19,947 [ERROR]
Traceback (most recent call last):
  File "C:\Users\steph\MS-Rewards-Farmer-master\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\MS-Rewards-Farmer-master\main.py", line 248, in executeBot
    searches.bingSearches()
  File "C:\Users\steph\MS-Rewards-Farmer-master\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Users\steph\MS-Rewards-Farmer-master\src\searches.py", line 173, in bingSearch
    searchbar.click()
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">vienna blood</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
        GetHandleVerifier [0x00428923+23283]
        (No symbol) [0x003EE934]
        (No symbol) [0x00320733]
        (No symbol) [0x003691C7]
        (No symbol) [0x003675D9]
        (No symbol) [0x003654CB]
        (No symbol) [0x00364AAF]
        (No symbol) [0x003599EF]
        (No symbol) [0x0038441C]
        (No symbol) [0x00359485]
        (No symbol) [0x003846B4]
        (No symbol) [0x0039CB8D]
        (No symbol) [0x003841B6]
        (No symbol) [0x00358017]
        (No symbol) [0x0035890D]
        GetHandleVerifier [0x0051A5E3+1013683]
        GetHandleVerifier [0x00523E3C+1052684]
        GetHandleVerifier [0x0051D4A4+1025652]
        GetHandleVerifier [0x0044EA2B+179195]
        (No symbol) [0x003F6833]
        (No symbol) [0x003F3198]
        (No symbol) [0x003F3337]
        (No symbol) [0x003EB4BE]
        BaseThreadInitThunk [0x76617BA9+25]
        RtlInitializeExceptionChain [0x7714C10B+107]
        RtlClearBits [0x7714C08F+191]

2024-08-08 14:43:19,950 [INFO] [POINTS] Data saved for the next day.

### Screenshots

2024-08-08 14:43:18,523 [DEBUG] terms=['riots in uk today', 'riots in uk', 'riots in london today update', 'riots games', 'riotgames.com login', 'riots in leeds', 'riots', 'rioty-select', 'riotlol kick', 'riotravel', 'riotclientservices exe', 'riotous meaning']
2024-08-08 14:43:18,523 [DEBUG] rootTerm=riot
2024-08-08 14:43:19,635 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.ElementClickInterceptedException'> exc_value=Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">vienna blood</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
        GetHandleVerifier [0x00428923+23283]
        (No symbol) [0x003EE934]
        (No symbol) [0x00320733]
        (No symbol) [0x003691C7]
        (No symbol) [0x003675D9]
        (No symbol) [0x003654CB]
        (No symbol) [0x00364AAF]
        (No symbol) [0x003599EF]
        (No symbol) [0x0038441C]
        (No symbol) [0x00359485]
        (No symbol) [0x003846B4]
        (No symbol) [0x0039CB8D]
        (No symbol) [0x003841B6]
        (No symbol) [0x00358017]
        (No symbol) [0x0035890D]
        GetHandleVerifier [0x0051A5E3+1013683]
        GetHandleVerifier [0x00523E3C+1052684]
        GetHandleVerifier [0x0051D4A4+1025652]
        GetHandleVerifier [0x0044EA2B+179195]
        (No symbol) [0x003F6833]
        (No symbol) [0x003F3198]
        (No symbol) [0x003F3337]
        (No symbol) [0x003EB4BE]
        BaseThreadInitThunk [0x76617BA9+25]
        RtlInitializeExceptionChain [0x7714C10B+107]
        RtlClearBits [0x7714C08F+191]
 traceback=<traceback object at 0x000002C4B3410800>
2024-08-08 14:43:19,947 [ERROR]
Traceback (most recent call last):
  File "C:\Users\steph\MS-Rewards-Farmer-master\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\MS-Rewards-Farmer-master\main.py", line 248, in executeBot
    searches.bingSearches()
  File "C:\Users\steph\MS-Rewards-Farmer-master\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Users\steph\MS-Rewards-Farmer-master\src\searches.py", line 173, in bingSearch
    searchbar.click()
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">vienna blood</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
        GetHandleVerifier [0x00428923+23283]
        (No symbol) [0x003EE934]
        (No symbol) [0x00320733]
        (No symbol) [0x003691C7]
        (No symbol) [0x003675D9]
        (No symbol) [0x003654CB]
        (No symbol) [0x00364AAF]
        (No symbol) [0x003599EF]
        (No symbol) [0x0038441C]
        (No symbol) [0x00359485]
        (No symbol) [0x003846B4]
        (No symbol) [0x0039CB8D]
        (No symbol) [0x003841B6]
        (No symbol) [0x00358017]
        (No symbol) [0x0035890D]
        GetHandleVerifier [0x0051A5E3+1013683]
        GetHandleVerifier [0x00523E3C+1052684]
        GetHandleVerifier [0x0051D4A4+1025652]
        GetHandleVerifier [0x0044EA2B+179195]
        (No symbol) [0x003F6833]
        (No symbol) [0x003F3198]
        (No symbol) [0x003F3337]
        (No symbol) [0x003EB4BE]
        BaseThreadInitThunk [0x76617BA9+25]
        RtlInitializeExceptionChain [0x7714C10B+107]
        RtlClearBits [0x7714C08F+191]

2024-08-08 14:43:19,950 [INFO] [POINTS] Data saved for the next day.

### Value of dashboard variable

na

**Comment by SteveeeeeS** [comment]
Ok, ii opened the trends file and deleted this one and it seemed to "redonload" a list of trends and continue working

**Comment by SteveeeeeS** [comment]
spoke to soon, failed on the first new file search;

2024-08-08 15:05:20,787 [DEBUG] terms=['shamima begum', 'shamima begum latest update', 'shamima begum breaking news', 'shamima begum husband', 'shamima begum case', 'shamima begum children', 'shamima begum glow up', 'shamima begum latest news today', 'shamima begum citizenship', 'shamima begum documentary', 'shamima begum latest', 'shamima begum parents']
2024-08-08 15:05:20,787 [DEBUG] rootTerm=shamima begum
2024-08-08 15:05:20,842 [DEBUG] term=shamima begum
2024-08-08 15:05:21,938 [DEBUG] [BING] Search attempt failed 1/8, sleeping 14.0625 seconds...
2024-08-08 15:05:36,048 [DEBUG] term=shamima begum latest update
2024-08-08 15:05:37,210 [DEBUG] [BING] Search attempt failed 2/8, sleeping 28.125 seconds...
2024-08-08 15:06:05,407 [DEBUG] term=shamima begum breaking news
2024-08-08 15:06:05,806 [DEBUG] [BING] Search attempt failed 3/8, sleeping 56.25 seconds...
2024-08-08 15:07:02,106 [DEBUG] term=shamima begum husband
2024-08-08 15:07:02,545 [DEBUG] [BING] Search attempt failed 4/8, sleeping 112.5 seconds...

**Comment by SteveeeeeS** [comment]
Nup, cant figure it out..

selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">matt hudson smith</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>

**Comment by SteveeeeeS** [comment]
No idea if its related, but i tried this so many times with fails. however hen clicking "see more" it passed the term, then froze on the next until i clicked it again and now it seems to be running though. the "see more" is still a button (not expanded like hen you click it)

**Comment by SteveeeeeS** [comment]
![image](https://github.com/user-attachments/assets/7d03a127-34fb-4f22-94d1-a8379a8fe42a)

**Comment by SteveeeeeS** [comment]
Stilll an issue today, i cant get it to do any searches at all. 
tried reinstalls, sessions, rebooting, closing chrome.exe's resetting chrome.

**Comment by cal4** [comment]
Try https://github.com/klept0/MS-Rewards-Farmer/tree/hotfix/element-click-intercepted to see if it fixes this issue

**Comment by SteveeeeeS** [comment]
> Try https://github.com/klept0/MS-Rewards-Farmer/tree/hotfix/element-click-intercepted to see if it fixes this issue

Think that fixed it mate.
Ill try again tomorrow when the rewards renew!
Good work!

**Comment by SteveeeeeS** [comment]
Sadly still happening..

> 2024-08-11 16:18:41,667 [INFO] [BING] 2/7
2024-08-11 16:18:48,393 [DEBUG] terms=['man united', 'man united fixtures', 'man united transfer news', 'man united news', 'man united vs liverpool', 'man united tickets', 'man united logo', 'man united players', 'man united score', 'man united vs coventry', 'man united fc', 'man united vs arsenal']
2024-08-11 16:18:48,394 [DEBUG] rootTerm=man united
2024-08-11 16:19:17,055 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.ElementNotInteractableException'> exc_value=Message: element not interactable
  (Session info: chrome=127.0.6533.100)
Stacktrace:
        GetHandleVerifier [0x00E58923+23283]
        (No symbol) [0x00E1E934]
        (No symbol) [0x00D505AD]
        (No symbol) [0x00D94334]
        (No symbol) [0x00D899EF]
        (No symbol) [0x00DB441C]
        (No symbol) [0x00D89485]
        (No symbol) [0x00DB46B4]
        (No symbol) [0x00DCCB8D]
        (No symbol) [0x00DB41B6]
        (No symbol) [0x00D88017]
        (No symbol) [0x00D8890D]
        GetHandleVerifier [0x00F4A5E3+1013683]
        GetHandleVerifier [0x00F53E3C+1052684]
        GetHandleVerifier [0x00F4D4A4+1025652]
        GetHandleVerifier [0x00E7EA2B+179195]
        (No symbol) [0x00E26833]
        (No symbol) [0x00E23198]
        (No symbol) [0x00E23337]
        (No symbol) [0x00E1B4BE]
        BaseThreadInitThunk [0x75AC7BA9+25]
        RtlInitializeExceptionChain [0x773BBB9B+107]
        RtlClearBits [0x773BBB1F+191]
 traceback=<traceback object at 0x000001F859976EC0>
2024-08-11 16:19:19,570 [ERROR]
Traceback (most recent call last):
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\utils.py", line 242, in click
    element.click()
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea id="sb_form_q" class="sb_form_q sb_form_ta" name="q" type="search" inputmode="search" maxlength="2000" autocomplete="off" autofocus="" aria-autocomplete="both" placeholder="Ask me anything..." aria-label="0 characters out of 2000" style="width: 464px;">...</textarea> is not clickable at point (1190, 306). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.100)
Stacktrace:
        GetHandleVerifier [0x00E58923+23283]
        (No symbol) [0x00E1E934]
        (No symbol) [0x00D50733]
        (No symbol) [0x00D991C7]
        (No symbol) [0x00D975D9]
        (No symbol) [0x00D954CB]
        (No symbol) [0x00D94AAF]
        (No symbol) [0x00D899EF]
        (No symbol) [0x00DB441C]
        (No symbol) [0x00D89485]
        (No symbol) [0x00DB46B4]
        (No symbol) [0x00DCCB8D]
        (No symbol) [0x00DB41B6]
        (No symbol) [0x00D88017]
        (No symbol) [0x00D8890D]
        GetHandleVerifier [0x00F4A5E3+1013683]
        GetHandleVerifier [0x00F53E3C+1052684]
        GetHandleVerifier [0x00F4D4A4+1025652]
        GetHandleVerifier [0x00E7EA2B+179195]
        (No symbol) [0x00E26833]
        (No symbol) [0x00E23198]
        (No symbol) [0x00E23337]
        (No symbol) [0x00E1B4BE]
        BaseThreadInitThunk [0x75AC7BA9+25]
        RtlInitializeExceptionChain [0x773BBB9B+107]
        RtlClearBits [0x773BBB1F+191]


During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\main.py", line 248, in executeBot
    searches.bingSearches()
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\searches.py", line 173, in bingSearch
    self.browser.utils.click(searchbar)
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\utils.py", line 244, in click
    self.tryDismissAllMessages()
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\utils.py", line 190, in tryDismissAllMessages
    self.tryDismissBingCookieBanner()
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\utils.py", line 201, in tryDismissBingCookieBanner
    self.webdriver.find_element(By.ID, "bnp_btn_accept").click()
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\steph\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementNotInteractableException: Message: element not interactable
  (Session info: chrome=127.0.6533.100)
Stacktrace:
        GetHandleVerifier [0x00E58923+23283]
        (No symbol) [0x00E1E934]
        (No symbol) [0x00D505AD]
        (No symbol) [0x00D94334]
        (No symbol) [0x00D899EF]
        (No symbol) [0x00DB441C]
        (No symbol) [0x00D89485]
        (No symbol) [0x00DB46B4]
        (No symbol) [0x00DCCB8D]
        (No symbol) [0x00DB41B6]
        (No symbol) [0x00D88017]
        (No symbol) [0x00D8890D]
        GetHandleVerifier [0x00F4A5E3+1013683]
        GetHandleVerifier [0x00F53E3C+1052684]
        GetHandleVerifier [0x00F4D4A4+1025652]
        GetHandleVerifier [0x00E7EA2B+179195]
        (No symbol) [0x00E26833]
        (No symbol) [0x00E23198]
        (No symbol) [0x00E23337]
        (No symbol) [0x00E1B4BE]
        BaseThreadInitThunk [0x75AC7BA9+25]
        RtlInitializeExceptionChain [0x773BBB9B+107]
        RtlClearBits [0x773BBB1F+191]

2024-08-11 16:19:19,598 [INFO] [POINTS] Data saved for the next day.

**Comment by SteveeeeeS** [comment]
> 2024-08-11 16:34:34,882 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-08-11 16:34:55,457 [DEBUG] in __exit__ exc_type=<class 'TypeError'> exc_value='NoneType' object is not subscriptable traceback=<traceback object at 0x000002418FC663C0>
2024-08-11 16:34:56,602 [ERROR]
Traceback (most recent call last):
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\main.py", line 248, in executeBot
    searches.bingSearches()
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\searches.py", line 132, in bingSearches
    remainingSearches = self.browser.getRemainingSearches()
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\MS-Rewards-Farmer-hotfix-element-click-intercepted\src\browser.py", line 243, in getRemainingSearches
    counters = dashboard["userStatus"]["counters"]
               ~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-08-11 16:34:56,611 [INFO] [POINTS] Data saved for the next day.

**Comment by cal4** [comment]
Might be separate issue: https://github.com/klept0/MS-Rewards-Farmer/issues/169#issuecomment-2282800173

Opened a PR, #176, and pushed what should be fix for https://github.com/klept0/MS-Rewards-Farmer/issues/169#issuecomment-2282797787

**Comment by SgtSobieski** [comment]
Worked for me 2 out of 2 times.

**Comment by SteveeeeeS** [comment]
Think this is solved, so will close

**Comment by cal4** [comment]
Leaving open till new release for better visibility
