### ISSUE TITLE
[BUG] Google trend not working

### ISSUE THREAD

**Issue by ProudNamed** [klept0/MS-Rewards-Farmer#173]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

fceb38f

### Describe the bug

Google trends return an error

### Copy and paste your error

2024-08-11 14:01:55,637 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\src\morePromotions.py", line 40, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\src\activities.py", line 26, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\src\utils.py", line 205, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-11 14:01:58,770 [DEBUG] promotionTitle=Take the tour
2024-08-11 14:01:58,770 [DEBUG] Already done, continuing
2024-08-11 14:01:58,770 [INFO] [MORE PROMOS] Exiting
2024-08-11 14:01:58,771 [DEBUG] googleTrendsShelf.__dict__ = {'dict': <dbm.dumb._Database object at 0x000001FC41181910>, '_protocol': 4, 'writeback': False, 'cache': {}, 'keyencoding': 'utf-8'}
2024-08-11 14:01:58,771 [DEBUG] google_trends = [('loadDate', datetime.date(2024, 8, 11))]
2024-08-11 14:01:58,772 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-08-11 14:02:06,782 [INFO] [BING] 1/23
2024-08-11 14:02:08,368 [DEBUG] terms=['load data', 'load dataset', 'loaddata函数', 'loaddata.com', 'loaddatetime', 'loaddate什么意思']
2024-08-11 14:02:08,368 [DEBUG] rootTerm=loadDate
2024-08-11 14:02:11,472 [DEBUG] term=load data
2024-08-11 14:02:28,643 [INFO] [BING] 2/23
2024-08-11 14:02:29,626 [DEBUG] in __exit__ exc_type=<class 'IndexError'> exc_value=list index out of range traceback=<traceback object at 0x000001FC45C69680>
2024-08-11 14:02:30,365 [ERROR] 
Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\main.py", line 248, in executeBot
    searches.bingSearches()
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Users\Admin\OneDrive - A\Desktop\MS-Rewards-Farmer-master\src\searches.py", line 147, in bingSearch
    rootTerm = list(self.googleTrendsShelf.keys())[0]
               ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

### Screenshots

![image](https://github.com/user-attachments/assets/61d50ca7-65f2-47da-8c44-6563861366f2)


### Value of dashboard variable

this break the search function

**Comment by ProudNamed** [comment]
it seem like the problem has naturally fixed itself
![image](https://github.com/user-attachments/assets/451286bc-c56e-4fb6-9ae0-fcdddb9acadd)

**Comment by cal4** [comment]
Yeah, for me getting google trends is pretty stable. It's possible to customize the bot depending on your network requirements, but like @klept0's saying I think it's counterproductive to add a list option when there's bigger fish to fry. Using google trends does make it harder to distinguish this bot from an actual human doing searches @badcaf3

**Comment by cal4** [comment]
@ProudNamed so these changes #164 might be contributing to this. Do you know the state of the searches when the exception occurred (i.e. how many desktop/mobile)?

**Comment by SteveeeeeS** [comment]
I do get search term fails a lot\constantly.. if its related, why would this happen?

2024-08-11 14:45:48,507 [DEBUG] term=olympic medal count 2028
2024-08-11 14:45:50,289 [DEBUG] [BING] Search attempt failed 7/8, sleeping 900.0 seconds...
2024-08-11 14:46:01,981 [DEBUG] term=olympic medal count 2029
2024-08-11 14:46:05,957 [DEBUG] [BING] Search attempt failed 8/8, sleeping 1800.0 seconds...
2024-08-11 14:46:18,214 [DEBUG] term=olympic medal count 2030
2024-08-11 14:46:20,975 [ERROR] [BING] Reached max search attempt retries

**Comment by SteveeeeeS** [comment]
Hmm, i constantly get it..

> 2024-08-11 14:56:24,784 [INFO] [BING] 12/27
2024-08-11 14:56:26,306 [DEBUG] terms=['spurs', 'spurs news', 'spurs fixtures', 'spurs shop', 'spursplay', 'spurs transfer news', 'spurs fc', 'spurs community', 'spurs media watch', 'spurs newsnow', 'spurs tickets', 'spursplay tv']
2024-08-11 14:56:26,374 [DEBUG] rootTerm=spurs
2024-08-11 14:56:48,556 [DEBUG] term=spurs
2024-08-11 14:57:11,395 [DEBUG] [BING] Search attempt failed 1/8, sleeping 14.0625 seconds...
2024-08-11 14:57:26,780 [DEBUG] term=spurs news
2024-08-11 14:57:33,865 [DEBUG] [BING] Search attempt failed 2/8, sleeping 28.125 seconds...
2024-08-11 14:57:55,451 [DEBUG] term=spurs fixtures
2024-08-11 14:58:04,485 [DEBUG] [BING] Search attempt failed 3/8, sleeping 56.25 seconds...
2024-08-11 14:58:25,797 [DEBUG] term=spurs shop
2024-08-11 14:58:32,826 [DEBUG] [BING] Search attempt failed 4/8, sleeping 112.5 seconds...
2024-08-11 14:58:55,164 [DEBUG] term=spursplay
2024-08-11 14:59:13,483 [DEBUG] [BING] Search attempt failed 5/8, sleeping 225.0 seconds...
2024-08-11 14:59:41,835 [DEBUG] term=spurs transfer news
2024-08-11 14:59:53,148 [DEBUG] [BING] Search attempt failed 6/8, sleeping 450.0 seconds...
2024-08-11 15:00:04,055 [DEBUG] term=spurs fc
2024-08-11 15:00:14,014 [DEBUG] [BING] Search attempt failed 7/8, sleeping 900.0 seconds...
2024-08-11 15:00:49,999 [DEBUG] term=spurs community
2024-08-11 15:01:19,440 [DEBUG] [BING] Search attempt failed 8/8, sleeping 1800.0 seconds...
2024-08-11 15:01:31,848 [DEBUG] term=spurs media watch
2024-08-11 15:01:32,617 [ERROR] [BING] Reached max search attempt retries
2024-08-11 15:01:32,617 [DEBUG] Moving passedInTerm to end of list

**Comment by cal4** [comment]
@badcaf3 @SteveeeeeS best to continue this line of discussion in #172 since unrelated to this issue (relatively)

**Comment by ProudNamed** [comment]
> @ProudNamed so these changes #164 might be contributing to this. Do you know the state of the searches when the exception occurred (i.e. how many desktop/mobile)?

hi sorry for late response, the state of the search was relatively normal, sometime it crash like shown in the bugs or it will just keep searching for ['load data', 'load dataset', 'loaddata函数', 'loaddata.com', 'loaddatetime', 'loaddate什么意思'] until it run out of searches

**Comment by cal4** [comment]
As a temp fix, next time delete all the files from project root starting with `google_trends`. If others have this issue I'll devote time making this more resilient.

**Comment by ProudNamed** [comment]
i tried deleting google_trends file like you said but the problem keep repeating, is there a possible permanent fix?
![image](https://github.com/user-attachments/assets/5e7aa851-918a-4d28-bf4d-58aa0d1a80f7)

**Comment by cal4** [comment]
Working on something in #184
