### ISSUE TITLE
[BUG] Cookies wont be accepted "Other element would receive the click:"

### ISSUE THREAD

**Issue by SgtSobieski** [klept0/MS-Rewards-Farmer#174]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Branch

master

### Commit

b989b1c

### Describe the bug

It seems the cookie overlay leads to the script crashing, as the search window cant be clicked. Region is Germany.

Maybe the latest version doesnt use the method "tryDismissAllMessages". 

### Copy and paste your error

2024-08-11 13:49:31,672 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-08-11 13:49:43,906 [INFO] [BING] 1/10
2024-08-11 13:49:45,456 [DEBUG] terms=['varfolomeev', 'varfolomeev darja', 'varfolomeev vladislav', 'varfolomeev video', 'varfolomeev youtube', 'varfolomeev wikipedia', 'varfolomeev vier wm-titel']
2024-08-11 13:49:45,461 [DEBUG] rootTerm=varfolomeev
2024-08-11 13:49:45,742 [DEBUG] term=varfolomeev
2024-08-11 13:49:48,432 [DEBUG] [BING] Search attempt failed 1/8, sleeping 14.0625 seconds...
2024-08-11 13:50:03,732 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.ElementClickInterceptedException'> exc_value=Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">varfolomeev</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
#0 0x55a50bccd6aa <unknown>
#1 0x55a50b99e600 <unknown>
#2 0x55a50b9f48e6 <unknown>
#3 0x55a50b9f27f6 <unknown>
#4 0x55a50b9f0277 <unknown>
#5 0x55a50b9ef11c <unknown>
#6 0x55a50b9e2be6 <unknown>
#7 0x55a50ba108a2 <unknown>
#8 0x55a50b9e2599 <unknown>
#9 0x55a50ba10a6e <unknown>
#10 0x55a50ba2f04a <unknown>
#11 0x55a50ba10643 <unknown>
#12 0x55a50b9e0d31 <unknown>
#13 0x55a50b9e179e <unknown>
#14 0x55a50bc9523b <unknown>
#15 0x55a50bc991d2 <unknown>
#16 0x55a50bc825f5 <unknown>
#17 0x55a50bc99d62 <unknown>
#18 0x55a50bc6723f <unknown>
#19 0x55a50bcbce48 <unknown>
#20 0x55a50bcbd020 <unknown>
#21 0x55a50bccc47c <unknown>
#22 0x7f6e1f83fac3 <unknown>
 traceback=<traceback object at 0x7fe69054dc80>
2024-08-11 13:50:04,086 [ERROR] 
Traceback (most recent call last):
  File "/xxx//main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
  File "/xxx//main.py", line 248, in executeBot
    searches.bingSearches()
  File "/xxx//src/searches.py", line 136, in bingSearches
    self.bingSearch()
  File "/xxx//src/searches.py", line 173, in bingSearch
    searchbar.click()
  File "/xxx/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "/xxx/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
  File "/xxx/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "/xxx/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <textarea class="b_searchbox" id="sb_form_q" name="q" enterkeyhint="" rows="1" data-min-rows="1" aria-autocomplete="both" aria-label="Enter your search here - Search suggestions will show as you type" type="search" inputmode="search" value="..." maxlength="2000" dir="" autocapitalize="off" autocorrect="off" autocomplete="off" spellcheck="false" placeholder="Ask me anything...">varfolomeev</textarea> is not clickable at point (442, 46). Other element would receive the click: <div class="bnp_overlay_wrapper"></div>
  (Session info: chrome=127.0.6533.99)
Stacktrace:
#0 0x55a50bccd6aa <unknown>

### Screenshots

![image](https://github.com/user-attachments/assets/7ddac945-064c-47b2-8ef9-0784b6685923)

### Value of dashboard variable

-

**Comment by SteveeeeeS** [comment]
Probably related to my logged bug: https://github.com/klept0/MS-Rewards-Farmer/issues/169

**Comment by cal4** [comment]
See #169 for hotfix
