### ISSUE TITLE
Frequently stop searching

### ISSUE THREAD

**Issue by Ices-Eyes** [klept0/MS-Rewards-Farmer#178]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "Title" and I edited it with the right error name.

### Branch

master

### Commit

Latest

### Describe the bug

Actually, I have frequently a timeout error during the search process, both desktop or mobile. Also, after that the script exit but no notificaton sended, either wit ALWAYS conf.

### Copy and paste your error

2024-08-11 22:58:02,348 [INFO] [BING] 12/14
2024-08-11 22:58:02,947 [DEBUG] terms=['stephen curry', 'stephen curry stats', 'stephen curry height', 'stephen curry underrated', 'stephen curry wallpaper', 'stephen curry shoes', 'stephen curry wallpaper 4k', 'stephen curry shooting form', 'stephen curry age', 'stephen curry under armour shoes', 'stephen curry net worth', 'stephen curry daughter']
2024-08-11 22:58:02,947 [DEBUG] rootTerm=stephen curry
2024-08-11 22:58:23,140 [DEBUG] in __exit__ exc_type=<class 'selenium.common.exceptions.TimeoutException'> exc_value=Message:
Stacktrace:
#0 0x5582c6a956aa <unknown>
#1 0x5582c6766600 <unknown>
#2 0x5582c67b5bcb <unknown>
#3 0x5582c67b5eb1 <unknown>
#4 0x5582c67f9b24 <unknown>
#5 0x5582c67d88cd <unknown>
#6 0x5582c67f704a <unknown>
#7 0x5582c67d8643 <unknown>
#8 0x5582c67a8d31 <unknown>
#9 0x5582c67a979e <unknown>
#10 0x5582c6a5d23b <unknown>
#11 0x5582c6a611d2 <unknown>
#12 0x5582c6a4a5f5 <unknown>
#13 0x5582c6a61d62 <unknown>
#14 0x5582c6a2f23f <unknown>
#15 0x5582c6a84e48 <unknown>
#16 0x5582c6a85020 <unknown>
#17 0x5582c6a9447c <unknown>
#18 0x7f62a2efb134 <unknown>
 traceback=<traceback object at 0x7ff320451900>
2024-08-11 22:58:23,569 [ERROR]
Traceback (most recent call last):
  File "/home/deb/MS-Rewards-Farmer-master/main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deb/MS-Rewards-Farmer-master/main.py", line 271, in executeBot
    searches.bingSearches()
  File "/home/deb/MS-Rewards-Farmer-master/src/searches.py", line 138, in bingSearches
    self.bingSearch()
  File "/home/deb/MS-Rewards-Farmer-master/src/searches.py", line 174, in bingSearch
    searchbar = self.browser.utils.waitUntilClickable(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deb/MS-Rewards-Farmer-master/src/utils.py", line 74, in waitUntilClickable
    return WebDriverWait(self.webdriver, timeToWait).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/deb/.local/lib/python3.11/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
#0 0x5582c6a956aa <unknown>
#1 0x5582c6766600 <unknown>
#2 0x5582c67b5bcb <unknown>
#3 0x5582c67b5eb1 <unknown>
#4 0x5582c67f9b24 <unknown>
#5 0x5582c67d88cd <unknown>
#6 0x5582c67f704a <unknown>
#7 0x5582c67d8643 <unknown>
#8 0x5582c67a8d31 <unknown>
#9 0x5582c67a979e <unknown>
#10 0x5582c6a5d23b <unknown>
#11 0x5582c6a611d2 <unknown>
#12 0x5582c6a4a5f5 <unknown>
#13 0x5582c6a61d62 <unknown>
#14 0x5582c6a2f23f <unknown>
#15 0x5582c6a84e48 <unknown>
#16 0x5582c6a85020 <unknown>
#17 0x5582c6a9447c <unknown>
#18 0x7f62a2efb134 <unknown>

2024-08-11 22:58:23,816 [INFO] [POINTS] Data saved for the next day.

### Screenshots

NA

### Value of dashboard variable

NA

**Comment by cal4** [comment]
Try upping the timeout time at that call

**Comment by Ices-Eyes** [comment]
You mean higher than the 20 seconds default? Would try, but it seems a consistently time already!
