### ISSUE TITLE
Mobile searches aren't starting

### ISSUE THREAD

**Issue by iDarkSnow** [klept0/MS-Rewards-Farmer#180]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Title

- [X] The title is no longer "Title" and I edited it with the right error name.

### Branch

master

### Commit

Latest

### Describe the bug

Whenever i execute the script without the -v parameter, which i require considering i run the script in the background and the browser always pops up at the worst moments, the desktop searches are executed but the mobile searches throw an error.

### Copy and paste your error

←[38;5;39m2024-08-14 15:53:06,880 [INFO] [BING] Finished Desktop Edge Bing searches !←[0m

DevTools listening on ws://127.0.0.1:51065/devtools/browser/a0823679-6fb8-4d71-97e3-ad30b17e30ac
[33560:1776:0814/155327.807:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.808:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.810:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.810:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.811:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.811:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.812:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.813:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.813:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.814:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.815:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.816:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.816:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.818:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.819:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.821:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.821:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
[33560:1776:0814/155327.822:ERROR:shared_image_manager.cc(223)] SharedImageManager::ProduceSkia: Trying to Produce a Skia representation from a non-existent mailbox.
←[38;5;226m2024-08-14 15:54:37,667 [WARNING] Failed to send to Discord notification: Bad Request - Unsupported Parameters., error=400.←[0m
←[38;5;196m2024-08-14 15:54:37,668 [ERROR] SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:51084
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x008D8923+23283]
        (No symbol) [0x0089E934]
        (No symbol) [0x007D05AD]
        (No symbol) [0x007BF99C]
        (No symbol) [0x008048F2]
        (No symbol) [0x007FBBC0]
        (No symbol) [0x007FBA17]
        (No symbol) [0x0083D9ED]
        (No symbol) [0x0083D21A]
        (No symbol) [0x008341B6]
        (No symbol) [0x00808017]
        (No symbol) [0x0080890D]
        GetHandleVerifier [0x009CA5F3+1013699]
        GetHandleVerifier [0x009D3E4C+1052700]
        GetHandleVerifier [0x009CD4B4+1025668]
        GetHandleVerifier [0x008FEA2B+179195]
        (No symbol) [0x008A6833]
        (No symbol) [0x008A3198]
        (No symbol) [0x008A3337]
        (No symbol) [0x0089B4BE]
        BaseThreadInitThunk [0x75EA7BA9+25]
        RtlInitializeExceptionChain [0x7730C10B+107]
        RtlClearBits [0x7730C08F+191]
←[0m
Traceback (most recent call last):
  File "C:\Microsoft Rewards\MS-Rewards-Farmer\main.py", line 42, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Microsoft Rewards\MS-Rewards-Farmer\main.py", line 243, in executeBot
    with Browser(mobile=True, account=currentAccount, args=args) as mobileBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Microsoft Rewards\MS-Rewards-Farmer\src\browser.py", line 42, in __init__
    self.webdriver = self.browserSetup()
                     ^^^^^^^^^^^^^^^^^^^
  File "C:\Microsoft Rewards\MS-Rewards-Farmer\src\browser.py", line 92, in browserSetup
    driver = webdriver.Chrome(
             ^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chrome\webdriver.py", line 45, in __init__
    super().__init__(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\chromium\webdriver.py", line 66, in __init__
    super().__init__(command_executor=executor, options=options)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 212, in __init__
    self.start_session(capabilities)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\undetected_chromedriver\__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 299, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 354, in execute
    self.error_handler.check_response(response)
  File "C:\Users\user\AppData\Local\Programs\Python\Python312\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.SessionNotCreatedException: Message: session not created: cannot connect to chrome at 127.0.0.1:51084
from chrome not reachable
Stacktrace:
        GetHandleVerifier [0x008D8923+23283]
        (No symbol) [0x0089E934]
        (No symbol) [0x007D05AD]
        (No symbol) [0x007BF99C]
        (No symbol) [0x008048F2]
        (No symbol) [0x007FBBC0]
        (No symbol) [0x007FBA17]
        (No symbol) [0x0083D9ED]
        (No symbol) [0x0083D21A]
        (No symbol) [0x008341B6]
        (No symbol) [0x00808017]
        (No symbol) [0x0080890D]
        GetHandleVerifier [0x009CA5F3+1013699]
        GetHandleVerifier [0x009D3E4C+1052700]
        GetHandleVerifier [0x009CD4B4+1025668]
        GetHandleVerifier [0x008FEA2B+179195]
        (No symbol) [0x008A6833]
        (No symbol) [0x008A3198]
        (No symbol) [0x008A3337]
        (No symbol) [0x0089B4BE]
        BaseThreadInitThunk [0x75EA7BA9+25]
        RtlInitializeExceptionChain [0x7730C10B+107]
        RtlClearBits [0x7730C08F+191]

### Screenshots

Can't take screenshots as the issues is only obtained without the -v parameter

### Value of dashboard variable

NA

**Comment by cal4** [comment]
Close all Chrome instances (or restart computer and try again)

**Comment by iDarkSnow** [comment]
I already imagine this wouldn't work as i always taskkill all chrome process at the beginning and at the end of the script, but i wanted to restart the pc anyway and try it but it didn't change anything :(

**Comment by klept0** [comment]
Try something for me - go to chrome://flags and search for the word open - try the option d3d9 and see if it helps


![image](https://github.com/user-attachments/assets/0f9fcc33-6be0-4106-85e2-c7c019b67d84)

**Comment by iDarkSnow** [comment]
Nothing changed, same error :(

**Comment by Frostbullet1** [comment]
![image](https://github.com/user-attachments/assets/73cd5f3f-a3aa-4396-b60a-606ab52ff633)
same here but not smart enough to know if its for the same reason

**Comment by cal4** [comment]
Try the develop branch, should be working there
