### ISSUE TITLE
AssertionError from apprise.notify(title=str(title), body=str(body))

### ISSUE THREAD

**Issue by HaveSomeRubicon** [klept0/MS-Rewards-Farmer#186]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

54e00cb

### Describe the bug

An AssertionError is being raised from file "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification.

### Copy and paste your error

2024-08-25 13:27:19,062 [INFO] ********************[I hid my email here]********************
2024-08-25 13:27:19,062 [DEBUG] in __init__

DevTools listening on ws://127.0.0.1:50852/devtools/browser/20126ca2-5c80-45b7-a757-8d493f0db626
2024-08-25 13:27:28,216 [INFO] Screen size: 2307x1319
2024-08-25 13:27:28,223 [INFO] Device size: 2252x1168
2024-08-25 13:27:28,257 [DEBUG] out __init__
2024-08-25 13:27:28,263 [DEBUG] in __enter__
2024-08-25 13:27:41,653 [INFO] [LOGIN] Logging-in...
2024-08-25 13:27:41,675 [INFO] [LOGIN] Entering email...
2024-08-25 13:27:52,072 [DEBUG] isPasswordless = False
2024-08-25 13:27:52,086 [INFO] [LOGIN] Entering password...
2024-08-25 13:28:03,322 [DEBUG] isDeviceAuthEnabled = False
2024-08-25 13:28:03,330 [DEBUG] isTOTPEnabled = True
2024-08-25 13:28:03,331 [INFO] [LOGIN] Entering OTP...
2024-08-25 13:28:12,736 [DEBUG] isAskingToProtect = False
2024-08-25 13:28:12,747 [INFO] [LOGIN] Logged-in successfully !
2024-08-25 13:28:16,015 [INFO] [POINTS] You have 0.00 points on your account
2024-08-25 13:28:16,015 [INFO] [DAILY SET] Trying to complete the Daily Set...
2024-08-25 13:28:18,266 [INFO] [DAILY SET] Exiting
2024-08-25 13:28:18,266 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...
2024-08-25 13:28:22,434 [INFO] [PUNCH CARDS] Exiting
2024-08-25 13:28:22,434 [INFO] [MORE PROMOS] Trying to complete More Promotions...
2024-08-25 13:28:24,372 [DEBUG] promotionTitle=You’ve earned enough points to redeem!
2024-08-25 13:28:24,372 [DEBUG] Already done, continuing
2024-08-25 13:28:24,372 [DEBUG] promotionTitle=Do you know the answer?
2024-08-25 13:28:24,373 [DEBUG] Already done, continuing
2024-08-25 13:28:24,373 [DEBUG] promotionTitle=Expand your vocabulary
2024-08-25 13:28:48,150 [DEBUG] promotionTitle=Stay on top of the elections
2024-08-25 13:28:48,150 [DEBUG] Already done, continuing
2024-08-25 13:28:48,150 [DEBUG] promotionTitle=What time is it?
2024-08-25 13:29:13,761 [DEBUG] promotionTitle=Earn More Rewards points on mobile
2024-08-25 13:29:13,761 [DEBUG] Already done, continuing
2024-08-25 13:29:13,761 [DEBUG] promotionTitle=Collect them all
2024-08-25 13:29:13,761 [DEBUG] Already done, continuing
2024-08-25 13:29:15,234 [DEBUG] in __exit__ exc_type=<class 'AssertionError'> exc_value= traceback=<traceback object at 0x00000182B72D0680>
2024-08-25 13:29:15,479 [ERROR] 
Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "d:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-08-25 13:29:15,482 [ERROR]
Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "d:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 356, in <module>
    main()
  File "d:\MS-Rewards-Farmer\main.py", line 43, in main
    Utils.sendNotification(
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "d:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "d:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 356, in <module>
    main()
  File "d:\MS-Rewards-Farmer\main.py", line 43, in main
    Utils.sendNotification(
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "d:\MS-Rewards-Farmer\main.py", line 359, in <module>
    Utils.sendNotification(
  File "d:\MS-Rewards-Farmer\src\utils.py", line 62, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

### Screenshots

![image](https://github.com/user-attachments/assets/917180f6-4106-4fb6-951e-23b32d08c7bb)

### Value of dashboard variable

https://gist.github.com/HaveSomeRubicon/f9a83517138126ab59b42835220ce175

**Comment by cal4** [comment]
Should be fixed, grab new release and retry please. Feel free to close issue if fixed.

**Comment by Ices-Eyes** [comment]
Hi, same problem here with the last version. It works ok, withot the assert before "assert apprise.notify(title=str(title), body=str(body))"

**Comment by cal4** [comment]
Which version, 1.0.0? @Ices-Eyes

**Comment by HaveSomeRubicon** [comment]
The error is gone on 0a94091. Thank you

**Comment by HaveSomeRubicon** [comment]
Sorry, it worked for a bit longer than usual and I closed the issue out of excitement. I got the error again but this time it was followed by a bunch of index errors during punch cards and promotions. Here is the full log.

`2024-08-26 09:23:49,037 [INFO] ********************email hidden********************
2024-08-26 09:23:49,037 [DEBUG] in __init__

DevTools listening on ws://127.0.0.1:61406/devtools/browser/3de90db0-3b8c-4f66-8848-d62e113b0789
2024-08-26 09:23:58,979 [INFO] Screen size: 2307x1319
2024-08-26 09:23:58,979 [INFO] Device size: 2252x1168
2024-08-26 09:23:58,997 [DEBUG] out __init__
2024-08-26 09:23:59,000 [DEBUG] in __enter__
2024-08-26 09:24:02,738 [INFO] [LOGIN] Already logged-in
2024-08-26 09:24:10,204 [INFO] [POINTS] You have 2,252.00 points on your account
2024-08-26 09:24:10,204 [INFO] [DAILY SET] Trying to complete the Daily Set...
2024-08-26 09:24:25,111 [ERROR] [DAILY SET] Error Daily Set of card 1
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\dailySet.py", line 27, in completeDailySet
    self.activities.openDailySetActivity(cardId)
  File "D:\MS-Rewards-Farmer\src\activities.py", line 22, in openDailySetActivity
    self.browser.utils.switchToNewTab(timeToWait=8)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:24:31,086 [ERROR] [DAILY SET] Error Daily Set of card 2
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\dailySet.py", line 27, in completeDailySet
    self.activities.openDailySetActivity(cardId)
  File "D:\MS-Rewards-Farmer\src\activities.py", line 22, in openDailySetActivity
    self.browser.utils.switchToNewTab(timeToWait=8)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:24:37,320 [ERROR] [DAILY SET] Error Daily Set of card 3
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\dailySet.py", line 27, in completeDailySet
    self.activities.openDailySetActivity(cardId)
  File "D:\MS-Rewards-Farmer\src\activities.py", line 22, in openDailySetActivity
    self.browser.utils.switchToNewTab(timeToWait=8)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:24:43,145 [INFO] [DAILY SET] Exiting
2024-08-26 09:24:43,145 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...
2024-08-26 09:24:57,213 [INFO] [PUNCH CARDS] Exiting
2024-08-26 09:24:57,213 [INFO] [MORE PROMOS] Trying to complete More Promotions...
2024-08-26 09:25:03,201 [DEBUG] promotionTitle=You’ve earned enough points to redeem!
2024-08-26 09:25:03,201 [DEBUG] Already done, continuing
2024-08-26 09:25:03,201 [DEBUG] promotionTitle=The roots of hip hop
2024-08-26 09:25:32,668 [DEBUG] promotionTitle=Marvel at jellylfish
2024-08-26 09:25:33,066 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:36,645 [DEBUG] promotionTitle=Complete this puzzle
2024-08-26 09:25:36,723 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:40,096 [DEBUG] promotionTitle=Expand your vocabulary
2024-08-26 09:25:40,121 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:43,438 [DEBUG] promotionTitle=Stay on top of the elections
2024-08-26 09:25:43,438 [DEBUG] Already done, continuing
2024-08-26 09:25:43,438 [DEBUG] promotionTitle=What time is it?
2024-08-26 09:25:43,535 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:46,834 [DEBUG] promotionTitle=Vegan sushi delights
2024-08-26 09:25:46,877 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:50,063 [DEBUG] promotionTitle=A step-by-step guide
2024-08-26 09:25:50,102 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:53,047 [DEBUG] promotionTitle=Feeling symptoms?
2024-08-26 09:25:53,071 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:25:55,126 [DEBUG] promotionTitle=Plan a quick getaway
2024-08-26 09:26:09,647 [DEBUG] promotionTitle=Plan a quick getaway
2024-08-26 09:26:10,119 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:26:13,397 [DEBUG] promotionTitle=Stay in touch on hot topics!
2024-08-26 09:26:13,473 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:26:15,025 [DEBUG] promotionTitle=Discover open job roles
2024-08-26 09:26:15,062 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "D:\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range
2024-08-26 09:26:17,570 [DEBUG] promotionTitle=Earn More Rewards points on mobile
2024-08-26 09:26:17,570 [DEBUG] Already done, continuing
2024-08-26 09:26:17,570 [DEBUG] promotionTitle=Time for some new shoes?
2024-08-26 09:26:17,570 [DEBUG] Already done, continuing
2024-08-26 09:26:17,570 [DEBUG] promotionTitle=Do you know the answer?
2024-08-26 09:26:17,571 [DEBUG] Already done, continuing
2024-08-26 09:26:21,072 [DEBUG] in __exit__ exc_type=<class 'AssertionError'> exc_value= traceback=<traceback object at 0x000001EDF5487380>
2024-08-26 09:26:22,765 [ERROR]
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
2024-08-26 09:26:22,782 [ERROR]
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 356, in <module>
    main()
  File "D:\MS-Rewards-Farmer\main.py", line 43, in main
    Utils.sendNotification(
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "D:\MS-Rewards-Farmer\main.py", line 245, in executeBot
    MorePromotions(desktopBrowser).completeMorePromotions()
  File "D:\MS-Rewards-Farmer\src\morePromotions.py", line 123, in completeMorePromotions
    Utils.sendNotification("Incomplete promotions(s)", incompletePromotions)
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 356, in <module>
    main()
  File "D:\MS-Rewards-Farmer\main.py", line 43, in main
    Utils.sendNotification(
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "D:\MS-Rewards-Farmer\main.py", line 359, in <module>
    Utils.sendNotification(
  File "D:\MS-Rewards-Farmer\src\utils.py", line 69, in sendNotification
    assert apprise.notify(title=str(title), body=str(body))
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError`

**Comment by Ices-Eyes** [comment]
> Which version, 1.0.0? @Ices-Eyes

Yep

**Comment by cal4** [comment]
@HaveSomeRubicon, do you have any `apprise.urls` configured? If so, mind sharing (remove passwords before)?

**Comment by HaveSomeRubicon** [comment]
Heres my config-private.yaml
```
# config-private.yaml
# Copy this file to config-private.yaml to use
apprise:
  urls:
    - "windows://" # Replace with your actual Apprise service URLs
```
And the config.yaml
```
# config.yaml
apprise:
  summary: ON_ERROR
retries:
  base_delay_in_seconds: 14.0625 # base_delay_in_seconds * 2^max = 14.0625 * 2^6 = 900 = 15 minutes
  max: 8
  strategy: EXPONENTIAL
```

**Comment by Hawkhawk812** [comment]
I'm having the same issue my first time trying to run the script. Im also getting AttributeError: 'Chrome' object has no attribute 'backend'.

**Comment by ProudNamed** [comment]
I'm also having this issue and it always happen randomly

**Comment by Kyrela** [comment]
So this error indicates that the message could not be sent to at least one of the addresses. This error could be caused by a *lot* of platform-specific issues. BUT, after a bit of research, it seems that it's most likely generated by Discord when trying to send the full traceback of an error, since a Discord message is limited to 2000 characters. So there are a few things to keep in mind:

1. Since the error can be generated by many things, and since the error doesn't produce a readable message or traceback, it probably **should not** stop the bot. Instead, it should log a generic error message explaining that the notification couldn't be sent.
2. The length of notification messages should be limited to avoid this kind of error. In particular, tracebacks should not be sent via apprise, or at least be truncated so that only the top-level trace is sent, not the whole stack plus the error message.
3. Discord notifications should be sent in embeds that allow a content length of 4096, excluding the title. Apprise makes this easy and generic by using `NotifyFormat.MARKDOWN`. Plus, it'll look a lot better, not just in Discord, but anywhere Markdown is supported. We'll just have to add \`\`\` around the tracebacks.

I'll probably start working on a PR to try out all this stuff when I have time, but if anyone wants to take care of it, feel free.
