### ISSUE TITLE
ipapi location rate limited

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#196]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

c9bc044f75292b4772adfd95a63e067526b3ecd6

### Describe the bug

When running the script multiple times a day (because of crashes) eventually the ipapi library will rate limit you for the rest of that day

### Copy and paste your error

2024-08-31 11:52:32,433 [INFO] [BING] Finished Desktop Edge Bing searches !
2024-08-31 11:53:11,378 [WARNING] Returning default
Traceback (most recent call last):
  File "C:\repos\MS-Rewards-Farmer\src\browser.py", line 207, in getCCodeLang
    nfo = ipapi.location()
          ^^^^^^^^^^^^^^^^
  File "C:\repos\MS-Rewards-Farmer\.venv\Lib\site-packages\ipapi\ipapi.py", line 87, in location
    raise RateLimited(data)
ipapi.exceptions.RateLimited: {'error': True, 'reason': 'RateLimited', 'message': 'Visit https://ipapi.co/ratelimited/ for details'}

### Screenshots

None

### Value of dashboard variable

None

**Comment by cal4** [comment]
Could cache the result of this call to disk, or refactor so that it isn't called as often per run (preferable in case bot moves between geographic locations between runs)

Could also switch to some other library that doesn't rate limit as much

**Comment by Kyrela** [comment]
Hi @Guido30, do you still have this problem with the latest version of the `develop` branch?

**Comment by Guido30** [comment]
This issue was fixed in the develop branch by using `locale.getlocale()` before falling back to the ipapi library
