### ISSUE TITLE
TypeError: 'NoneType' object is not subscriptable

### ISSUE THREAD

**Issue by Yarmash10** [klept0/MS-Rewards-Farmer#197]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

v1.0.1

### Describe the bug

Downloaded a new copy of 1.0.1. Previously using pre-release versions with success. Installed and upgraded all requirements. Login is fine, but there is an error every time it checks for daily promotions. I also note that it reports my current points a 0, so it's maybe not talking to the dashboard correctly.

### Copy and paste your error

2024-09-01 17:23:35,743 [INFO] ********************@outlook.com********************
2024-09-01 17:23:35,743 [DEBUG] in __init__
2024-09-01 17:23:51,953 [INFO] Screen size: 1890x958
2024-09-01 17:23:51,998 [INFO] Device size: 1835x807
2024-09-01 17:23:52,411 [DEBUG] out __init__
2024-09-01 17:23:52,411 [DEBUG] in __enter__
2024-09-01 17:24:45,744 [INFO] [LOGIN] Already logged-in
2024-09-01 17:25:23,318 [INFO] [POINTS] You have 0.00 points on your account
2024-09-01 17:25:23,318 [INFO] [DAILY SET] Trying to complete the Daily Set...
2024-09-01 17:26:36,653 [DEBUG] in __exit__ exc_type=<class 'TypeError'> exc_value='NoneType' object is not subscriptable traceback=<traceback object at 0x000001A24118AA00>
2024-09-01 17:26:37,143 [ERROR] 
Traceback (most recent call last):
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-master\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-master\main.py", line 243, in executeBot
    DailySet(desktopBrowser).completeDailySet()
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-master\src\dailySet.py", line 18, in completeDailySet
    data = self.browser.utils.getDashboardData()["dailySetPromotions"]
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
2024-09-01 17:26:37,161 [WARNING] config-private.yaml doesn't exist
2024-09-01 17:26:37,161 [DEBUG] No urls found, not sending notification
2024-09-01 17:26:37,161 [INFO] [POINTS] Data saved for the next day.

### Screenshots

n/a

### Value of dashboard variable

Too long to paste

**Comment by cal4** [comment]
I came across this too. For whatever reason it takes src.utils.Utils.getBingInfo an hour or so after login to return meaningful information. Try rerunning and see what happens.

**Comment by Yarmash10** [comment]
After clearing sessions again it seems to be working now. It now throws a similar error during mobile searches. This is after the previous version of the script has already done all the mobile searches for the day, so not sure if that is a factor. i will test again tomorrow.

2024-09-11 16:44:48,697 [INFO] [READ TO EARN] Completed the Read to Earn successfully !
2024-09-11 16:44:48,713 [INFO] [BING] Starting Mobile Edge Bing searches...
2024-09-11 16:45:37,408 [DEBUG] in __exit__ exc_type=<class 'TypeError'> exc_value='NoneType' object is not subscriptable traceback=<traceback object at 0x0000027A4B765AC0>
2024-09-11 16:45:38,182 [ERROR] 
Traceback (most recent call last):
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-1.1.0\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-1.1.0\main.py", line 267, in executeBot
    searches.bingSearches()
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-1.1.0\src\searches.py", line 119, in bingSearches
    while (remainingSearches := self.browser.getRemainingSearches()) > 0:
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\FTP\Documents\MS-Rewards-Farmer-1.1.0\src\browser.py", line 236, in getRemainingSearches
    counters = dashboard["userStatus"]["counters"]
               ~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable

**Comment by cal4** [comment]
Yeah saw same thing

**Comment by Kyrela** [comment]
@Yarmash10, do you still have this problem with the latest version of the `develop` branch?

**Comment by Yarmash10** [comment]
@Kyrela, I've been using the develop branch now for a while with no issue. Bug can be closed.

**Comment by gh0sti** [comment]
I'd like to reopen this issue, I am seeing this on dev/master 2.0 that was released. I have one account that finishes desktop and won't move to mobile searches. It errors out with the TypeError as shown above. I am able to continue searching once I pass Main.py -t mobile to finish up searches.
