### ISSUE TITLE
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by ProudNamed** [klept0/MS-Rewards-Farmer#199]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

c9bc044

### Describe the bug

the bug just randomly happen during searches and most of the time the searches aren't completed

### Copy and paste your error

2024-09-05 18:55:19,910 [DEBUG] in __exit__ exc_type=<class 'requests.exceptions.JSONDecodeError'> exc_value=Expecting value: line 1 column 1 (char 0) traceback=<traceback object at 0x000001B70C3DAF80>
2024-09-05 18:55:25,781 [ERROR] 
Traceback (most recent call last):
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 974, in json
    return complexjson.loads(self.text, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\json\__init__.py", line 346, in loads
    return _default_decoder.decode(s)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.12_3.12.1520.0_x64__qbz5n2kfra8p0\Lib\json\decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\main.py", line 249, in executeBot
    searches.bingSearches()
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\src\searches.py", line 205, in bingSearch
    pointsAfter = self.browser.utils.getAccountPoints()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\src\utils.py", line 176, in getAccountPoints
    return self.getBingInfo()["balance"]
           ^^^^^^^^^^^^^^^^^^
  File "C:\Users\Admin\OneDrive - A\Desktop\FARMER pro 1.0.1\src\utils.py", line 148, in getBingInfo
    return response.json()["userInfo"]
           ^^^^^^^^^^^^^^^
  File "C:\Users\Admin\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\requests\models.py", line 978, in json
    raise RequestsJSONDecodeError(e.msg, e.doc, e.pos)
requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### Screenshots

None

### Value of dashboard variable

None

**Comment by Kyrela** [comment]
Hi @ProudNamed, do you still have this problem with the latest version of the `develop` branch?
