### ISSUE TITLE
[v1.1.0] Error: Can't get google trends; 'AssertionError'

### ISSUE THREAD

**Issue by 28Black** [klept0/MS-Rewards-Farmer#206]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

0f0052c

### Describe the bug

When the script comes to the point where the searches should be done, it shows an error and force-closes. 

### Copy and paste your error

2024-09-09 15:11:00,419 [INFO] [BING] Remaining searches=26
2024-09-09 15:11:04,751 [DEBUG] google_trends before load = []
2024-09-09 15:11:05,001 [DEBUG] in __exit__ exc_type=<class 'AssertionError'> exc_value= traceback=<traceback object at 0x0000026109608D80>
2024-09-09 15:11:06,472 [ERROR] 
Traceback (most recent call last):
  File "C:\Users\LKA-Berlin0472\Desktop\MS-Rewards-Farmer-1.1.0\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LKA-Berlin0472\Desktop\MS-Rewards-Farmer-1.1.0\main.py", line 249, in executeBot
    searches.bingSearches()
  File "C:\Users\LKA-Berlin0472\Desktop\MS-Rewards-Farmer-1.1.0\src\searches.py", line 129, in bingSearches
    trends = self.getGoogleTrends(desktopAndMobileRemaining.getTotal())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\LKA-Berlin0472\Desktop\MS-Rewards-Farmer-1.1.0\src\searches.py", line 82, in getGoogleTrends
    r.status_code == requests.codes.ok
AssertionError
2024-09-09 15:11:06,477 [WARNING] config-private.yaml doesn't exist
2024-09-09 15:11:06,480 [DEBUG] No urls found, not sending notification
2024-09-09 15:11:06,482 [INFO] [POINTS] Data saved for the next day.

### Screenshots

none

### Value of dashboard variable

none

**Comment by cal4** [comment]
Adjust retry config in src.utils.Utils.makeRequestsSession

**Comment by 28Black** [comment]
> Adjust retry config in src.utils.Utils.makeRequestsSession

I played around with values of total=x, backoff_factor=y (in case that was what you mean with your comment)

No luck so farm the error persists.

**Comment by cal4** [comment]
What'd you adjust the values to?
________________________________

**Comment by ShinyJustyZ** [comment]
Can confirm the error. Changing the count to 200 didn't fix it. I don't know what backoff factor does, so I kept it at 1

**Comment by cal4** [comment]
Works for me, I'd suggest trying the develop branch.

**Comment by 28Black** [comment]
> What'd you adjust the values to?

I tried the values of the previous releases and then 
total= from 1 to 50
backoff_factor= from 0.1 to 2.5

I'll try the dev branch next as you suggested.

**Comment by SteveTryndamere** [comment]
> Works for me, I'd suggest trying the develop branch.
> 
> You can also look at the code and try getting Google trends via a browser to see if the problem's isolated.

I encountered the same issue on dev. didn't work it out by tweaking retry config.
i checked the code: status_code=400, requests.codes.ok=200
"400 Bad Request: This HTTP status code indicates that the server could not understand the request due to invalid syntax. The client should not repeat the request without modifications."
