### ISSUE TITLE
Doesn't start, account error

### ISSUE THREAD

**Issue by hdhdsdasd** [klept0/MS-Rewards-Farmer#210]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [x] I've cleared the sessions folder.

### Branch

master

### Commit

0f0052c

### Describe the bug

I installed all requirements and updated the account.json file but when I run main.py I get this error.

### Copy and paste your error

C:\Users\user\Documents\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0>python main.py
Traceback (most recent call last):
  File "C:\Users\user\Documents\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\main.py", line 14, in <module>
    from src import (
  File "C:\Users\user\Documents\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\__init__.py", line 1, in <module>
    from .account import Account
  File "C:\Users\user\Documents\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\account.py", line 5, in <module>
    class Account:
  File "C:\Users\user\Documents\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\account.py", line 8, in Account
    totp: str | None = None
TypeError: unsupported operand type(s) for |: 'type' and 'NoneType'

### Screenshots

Browser doesn't start

### Value of dashboard variable

N/A?

**Comment by klept0** [comment]
try the dev branch - also make sure you have closed out all open copies of chrome and give it another shot

**Comment by hdhdsdasd** [comment]
Tried both, same issue sadly.

**Comment by cal4** [comment]
Which version of Python are you using?

**Comment by hdhdsdasd** [comment]
3.9

**Comment by cal4** [comment]
https://stackoverflow.com/a/76712732/4164390

**Comment by hdhdsdasd** [comment]
Tried it with 3.10 and 3.11, same issue.

**Comment by cal4** [comment]
Using the absolute reference to python 3.10, or the one on the path?

**Comment by Kyrela** [comment]
@hdhdsdasd, as Cal said, can you try with the absolute reference to python 3.10?

**Comment by Kyrela** [comment]
Closing it as it seems to be related to the python version, and there isn't any update on it.
