### ISSUE TITLE
Login Stopped Working

### ISSUE THREAD

**Issue by jdeath** [klept0/MS-Rewards-Farmer#215]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

develop

### Commit

494c9d

### Describe the bug

Been working flawlessly for a while, now login does not work.

### Copy and paste your error

Windows:
`
Traceback (most recent call last):
  File "C:\Users\xxx\Desktop\MS-Rewards-Farmer-develop\main.py", line 236, in executeBot
    Login(desktopBrowser, args).login()
  File "C:\Users\xxxx\Desktop\MS-Rewards-Farmer-develop\src\login.py", line 71, in login
    self.execute_login()
  File "C:\Users\xxx\Desktop\MS-Rewards-Farmer-develop\src\login.py", line 176, in execute_login
    self.utils.waitUntilVisible(By.NAME, "kmsiForm")
  File "C:\Users\xxx\Desktop\MS-Rewards-Farmer-develop\src\utils.py", line 125, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\xxx\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message:
Stacktrace:
`
linux (docker) - Session not cleared:
File "/app/main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 236, in executeBot
    Login(desktopBrowser, args).login()
  File "/app/src/login.py", line 71, in login
    self.execute_login()
  File "/app/src/login.py", line 83, in execute_login
    emailField = self.utils.waitUntilVisible(By.ID, "i0116")
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils.py", line 125, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
`

linux (sessions folder cleared)
`
Traceback (most recent call last):
  File "/app/main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/main.py", line 236, in executeBot
    Login(desktopBrowser, args).login()
  File "/app/src/login.py", line 71, in login
    self.execute_login()
  File "/app/src/login.py", line 176, in execute_login
    self.utils.waitUntilVisible(By.NAME, "kmsiForm")
  File "/app/src/utils.py", line 125, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
`

### Screenshots

chrome window didn't load for me

### Value of dashboard variable

xxxx

**Comment by Haxonium** [comment]
Same thing happens to me on master

**Comment by klept0** [comment]
Run it with -v | You most likely have a prompt on the screen that has not been accounted for yet such as the "We are updating our TOS"

**Comment by jdeath** [comment]
Figured out issue. There is an update of the terms of service dialog. I am sure there is a way to check for it, but for now.

1. On a desktop, clear all your data on a browser
2. log into rewards.bing.com
3. It will prompt you to agree to the new terms
4. Continue to log in
5. Now start the rewards farmer. Even on another computer, it will now login since you already accepted the new terms

But I am now getting an error that 
`
File "/app/src/browser.py", line 281, in getRemainingSearches
    pcSearch: dict = counters["PCSearch"][0]
`

but at least log in works.
