### ISSUE TITLE
Lvl 1 Accounts not working due to mobile searches

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#217]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

develop

### Commit

49e4930345c033769adc231723458e5ff342b731

### Describe the bug

Lvl 1 Bing Rewards account dont work with the script since they re not allowed to farm points using the mobile searches yet, only the pc search searches are found

### Copy and paste your error

2024-10-25 17:56:03,644 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-10-25 17:56:08,000 [ERROR] 
Traceback (most recent call last):
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 246, in executeBot
    searches.bingSearches()
  File "C:\Repositories\MS-Rewards-Farmer\src\searches.py", line 110, in bingSearches
    desktopAndMobileRemaining = self.browser.getRemainingSearches(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\src\browser.py", line 268, in getRemainingSearches
    mobileSearch: dict = counters["MobileSearch"][0]
                         ~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'MobileSearch'

### Screenshots

![image](https://github.com/user-attachments/assets/842ffad7-8f1e-4a87-8a2c-44f64590794e)


### Value of dashboard variable

.

**Comment by klept0** [comment]
Try dev build and run the desktop only flag

**Comment by Ices-Eyes** [comment]
I've solved this problem by a simple mod on the browser.py in function getRemainingSearches:

```
try:
    mobileSearch: dict = counters["mobileSearch"][0]
except:
    mobileSearch = None
pointProgressMax: int = pcSearch["pointProgressMax"]

[...]

if mobileSearch is None:
    mobilePointsRemaining = 0
else:
    mobilePointsRemaining = (
        mobileSearch["pointProgressMax"] - mobileSearch["pointProgress"]
    )
```

**Comment by cal4** [comment]
Good try, but it's better to raise an exception if these fields aren't as we expect, rather than hide it since it'll definitely cause problems with execution later. Checkout this for more general reasoning: https://stackoverflow.com/a/77361/4164390.

I've made a change to develop so that getRemainingSearches should be more reliable (without returning None/0)

**Comment by Ices-Eyes** [comment]
The fact is that on account of level 1, the mobileSearch aren't counted for rewards, hence the dashboard has't that section... so here we cannot expect that the mobileSearch section is present, in my opinion.
Maybe instead of catching the exception we could use the userStatus.levelInfo.activeLevel info...

**Comment by cal4** [comment]
Ah right, I see now. Hmm

**Comment by cal4** [comment]
Should be fixed, give develop a try. See https://github.com/klept0/MS-Rewards-Farmer/commit/81afb3279c5666e079105c13bb86a7554e2bdc1e.

Thanks for the contribution @Ices-Eyes. Modified it a bit to check for level.

**Comment by Kyrela** [comment]
Hi @Guido30, can you confirm that the issue you are experiencing has been resolved?

**Comment by Guido30** [comment]
Yes
