### ISSUE TITLE
IndexError when doing More Promotions

### ISSUE THREAD

**Issue by Wyatt-Stanke** [klept0/MS-Rewards-Farmer#223]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

24a63e4

### Describe the bug

When running the program, when it's doing all the promotions, it doesn't actually do anything and just refreshes the website over and over again. It seems it's trying to click a link that opens a new tab, but the new tab isn't opening for some reason.

### Copy and paste your error

```2024-11-10 11:00:15,693 [ERROR] [MORE PROMOS] Error More Promotions
Traceback (most recent call last):
  File "C:\Users\wyatt\Documents\MS-Rewards-Farmer\src\morePromotions.py", line 39, in completeMorePromotions
    self.activities.openMorePromotionsActivity(
  File "C:\Users\wyatt\Documents\MS-Rewards-Farmer\src\activities.py", line 29, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab(timeToWait=5)
  File "C:\Users\wyatt\Documents\MS-Rewards-Farmer\src\utils.py", line 216, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range```

### Screenshots

The only thing happening in the browser was it was refreshing the bing rewards website over and over again while it was erroring. The bing rewards website was the only tab open.

### Value of dashboard variable

https://gist.github.com/Wyatt-Stanke/8c66c46545dd82b0e04d66ed6c767b9e

**Comment by jnelson89** [comment]
Timeout for Supersonic quiz
Index Error for More Promotions Activities
```
2024-12-03 05:36:38,985 [INFO] [DAILY SET] Trying to complete the Daily Set...
2024-12-03 05:37:27,265 [ERROR] [ACTIVITY] Error doing Supersonic quiz
Traceback (most recent call last):
  File "/app/src/activities.py", line 208, in doActivity
    self.completeQuiz()
    ~~~~~~~~~~~~~~~~~^^
  File "/app/src/activities.py", line 80, in completeQuiz
    self.browser.utils.waitUntilVisible(By.ID, "overlayPanel", 5)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/app/src/utils.py", line 76, in waitUntilVisible
    return WebDriverWait(self.webdriver, timeToWait).until(
           ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^
        expected_conditions.visibility_of_element_located((by, selector))
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    )
    ^
  File "/home/user/.local/lib/python3.13/site-packages/selenium/webdriver/support/wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: 
Stacktrace:
#0 0x55a24bcef31a <unknown>
#1 0x55a24b8056e0 <unknown>
#2 0x55a24b8543e6 <unknown>
#3 0x55a24b854681 <unknown>
#4 0x55a24b899b04 <unknown>
#5 0x55a24b87848d <unknown>
#6 0x55a24b896ed7 <unknown>
#7 0x55a24b878203 <unknown>
#8 0x55a24b846cc0 <unknown>
#9 0x55a24b847c9e <unknown>
#10 0x55a24bcbcd0b <unknown>
#11 0x55a24bcc0c92 <unknown>
#12 0x55a24bca9b3c <unknown>
#13 0x55a24bcc1807 <unknown>
#14 0x55a24bc8f0df <unknown>
#15 0x55a24bcde578 <unknown>
#16 0x55a24bcde740 <unknown>
#17 0x55a24bcee196 <unknown>
#18 0x7f3f55cd01c4 <unknown>

2024-12-03 05:45:33,095 [INFO] [DAILY SET] Done
2024-12-03 05:45:33,095 [INFO] [MORE PROMOS] Trying to complete More Promotions...
2024-12-03 05:45:56,925 [ERROR] [ACTIVITY] Error doing Save the Amur leopard
Traceback (most recent call last):
  File "/app/src/activities.py", line 188, in doActivity
    self.openMorePromotionsActivity(cardId)
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^
  File "/app/src/activities.py", line 64, in openMorePromotionsActivity
    self.browser.utils.switchToNewTab()
    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^
  File "/app/src/utils.py", line 206, in switchToNewTab
    self.webdriver.switch_to.window(window_name=self.webdriver.window_handles[1])
                                                ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
IndexError: list index out of range

```

**Comment by Kyrela** [comment]
Hi @maephisto666, do you still have this problem with the latest version of the `develop` branch?

**Comment by hdhdsdasd** [comment]
I had the same issue. It fixed thast issue when I ran the dev rbanch but I got this one instead [](https://pastebin.com/SYE0ci2a)
