### ISSUE TITLE
[Fixed] TimeoutError on every desktop search run

### ISSUE THREAD

**Issue by 28Black** [klept0/MS-Rewards-Farmer#228]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

24a63e4

### Describe the bug

Every time I run the desktop searches, at one point, the given error occurs. **It only happens during desktop searches; mobile searches are never affected.** 

The following happens in the browser: After a search, the bing.com search page is switched back to rewards.bing.com (presumably to retrieve the dashboard data?). Here, the page (rewards.bing.com) loads indefinitely until the given error occurs and the script terminates.

_**Manual workaround**_:
If you happen to notice the infinite loading, it can be canceled manually by clicking on the reload page button. If you then manually navigate to the 'bing.com' page, the script will continue to run normally. At least until the error occurs again, and you have to repeat the procedure.

I can reproduce this error (using master branch) on the following devices: Desktop PC, Laptop and Raspberry Pi 5.

### Copy and paste your error

2024-11-28 18:42:04,426 [INFO] [BING] Remaining searches=20
2024-11-28 18:44:07,775 [DEBUG] in __exit__ exc_type=<class 'urllib3.exceptions.ReadTimeoutError'> exc_value=HTTPConnectionPool(host='localhost', port=33927): Read timed out. (read timeout=120) traceback=<traceback object at 0x7fff54148800>
2024-11-28 18:47:07,766 [ERROR] 
Traceback (most recent call last):
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 536, in _make_request
    response = conn.getresponse()
               ^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connection.py", line 507, in getresponse
    httplib_response = super().getresponse()
                       ^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 1374, in getresponse
    response.begin()
  File "/usr/lib/python3.11/http/client.py", line 318, in begin
    version, status, reason = self._read_status()
                              ^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/http/client.py", line 279, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.11/socket.py", line 706, in readinto
    return self._sock.recv_into(b)
           ^^^^^^^^^^^^^^^^^^^^^^^
TimeoutError: timed out

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/main.py", line 250, in executeBot
    searches.bingSearches()
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/src/searches.py", line 121, in bingSearches
    desktopAndMobileRemaining = self.browser.getRemainingSearches(
                                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/src/browser.py", line 234, in getRemainingSearches
    dashboard = self.utils.getDashboardData()
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/src/utils.py", line 135, in getDashboardData
    self.webdriver.get(urlBefore)
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 393, in get
    self.execute(Command.GET, {"url": url})
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 382, in execute
    response = self.command_executor.execute(driver_command, params)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 404, in execute
    return self._request(command_info[0], url, body=data)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/remote_connection.py", line 428, in _request
    response = self._conn.request(method, url, body=body, headers=headers, timeout=self._client_config.timeout)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/_request_methods.py", line 143, in request
    return self.request_encode_body(
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/_request_methods.py", line 278, in request_encode_body
    return self.urlopen(method, url, **extra_kw)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/poolmanager.py", line 443, in urlopen
    response = conn.urlopen(method, u.request_uri, **kw)
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 843, in urlopen
    retries = retries.increment(
              ^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/util/retry.py", line 474, in increment
    raise reraise(type(error), error, _stacktrace)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/util/util.py", line 39, in reraise
    raise value
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 789, in urlopen
    response = self._make_request(
               ^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 538, in _make_request
    self._raise_timeout(err=e, url=url, timeout_value=read_timeout)
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/urllib3/connectionpool.py", line 369, in _raise_timeout
    raise ReadTimeoutError(
urllib3.exceptions.ReadTimeoutError: HTTPConnectionPool(host='localhost', port=33927): Read timed out. (read timeout=120)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/src/browser.py", line 71, in __exit__
    self.webdriver.close()
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 495, in close
    self.execute(Command.CLOSE)
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 384, in execute
    self.error_handler.check_response(response)
  File "/home/unicornpoop/Skripte/MS-Rewards-Farmer/.env/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 232, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.InvalidSessionIdException: Message: invalid session id
Stacktrace:
#0 0x5556006a2b50 <unknown>
#1 0x55560021fe7c <unknown>
#2 0x55560025774c <unknown>
#3 0x5556002586c8 <unknown>
#4 0x555600676958 <unknown>
#5 0x555600679948 <unknown>
#6 0x55560067952c <unknown>
#7 0x555600668640 <unknown>
#8 0x555600679f84 <unknown>
#9 0x5556006530a0 <unknown>
#10 0x555600692404 <unknown>
#11 0x5556006925ec <unknown>
#12 0x5556006a1b44 <unknown>
#13 0x7fff8d2dee8c <unknown>
#14 0x7fff8d347b18 <unknown>

2024-11-28 18:47:07,784 [INFO] [POINTS] Data saved for the next day.

### Screenshots

none

### Value of dashboard variable

-

**Comment by 28Black** [comment]
### Solution
So, after a long time, I have finally been able to find a "fix" for the timeout exception bug. As a "non-developer", I wouldn't have been able to do this on my own here. So, **special thanks go to DeepSeek Ai**, which helped me a lot in narrowing down and catching the bug.

What was the error?
This error occurs when the bot attempts to make an HTTP request (https://rewards.bing.com/), but the response is not received by the server within the specified time limit (in this case 120 seconds). If you manually abort loading the rewards site and switch to bing.com, the bot continues to run. This shows that the problem is not in the functionality of the bot, but in the waiting time or the way the bot deals with timeouts and/or switching between the rewards page and search page.

Our changes to fix the bug:

### **1. Set a timeout for loading the page**
We need to modify the code so that the bot does not wait indefinitely for the page to load, but stops loading after a certain time and continues. This could be achieved with the **set_page_load_timeout method** of the web driver. When the timeout is reached, a TimeoutException is thrown, which we can intercept and handle accordingly.
So we added a timeout for loading the page in the **browser.py** file (where the web driver is initialized), in **line 115**:

```
[rest of the code] 

       driver = webdriver.Chrome(
            options=options,
            seleniumwire_options=seleniumwireOptions,
            user_data_dir=self.userDataDir.as_posix(),
            version_main=major,
        )

        # Set the timeout for loading the page to 45 seconds
        driver.set_page_load_timeout(45)

        seleniumLogger = logging.getLogger("seleniumwire")
        seleniumLogger.setLevel(logging.ERROR)

[rest of the code] 
```

### **2. Catching and handling the TimeoutException**
In the **utils.py** file (where the error occurs), we catch the TimeoutException in **getDashboardData**  amd **goToSearch** and try to reload the page or continue to direct to the search site:

```
    def getDashboardData(self) -> dict:
        urlBefore = self.webdriver.current_url
        try:
            logging.debug("Navigating to rewards page...")
            self.goToRewards()
            logging.debug("Executing script to get dashboard data...")
            return self.webdriver.execute_script("return dashboard")
        except TimeoutException:
            logging.warning("Timeout occurred while loading rewards page. Retrying...")
            self.webdriver.execute_script("window.stop()")  # Stops loading the page
            self.goToRewards()  # Try to navigate to the rewards page again
            return self.webdriver.execute_script("return dashboard")
        except Exception as e:
            logging.error(f"Error in getDashboardData: {e}")
            raise
        finally:
            try:
                logging.debug(f"Returning to original URL: {urlBefore}")
                self.webdriver.get(urlBefore)
            except TimeoutException as e:
                logging.warning(f"Timeout occurred while returning to original URL: {e}")
                self.goToSearch()

```
and 

```
    def goToSearch(self) -> None:
        try:
            logging.debug("Navigating to search page...")
            self.webdriver.get("https://www.bing.com/")
        except TimeoutException:
            logging.warning("Timeout occurred while loading search page. Retrying...")
            self.webdriver.execute_script("window.stop()")  # Stops loading the page
            self.webdriver.get("https://www.bing.com/")   # Try to navigate to the search page again
    

```
**Also, we added additional logging information to identify the exact point of the error; feel free to remove them or comment them out.**

### _**[Optional]**_
3. Increase the waiting time between searches
The waiting time between search queries is defined in the searches.py file. Increased this waiting time to reduce the load on the server and better obfuscation to imitate human reaction times, line 137:

`time.sleep(random.randint(15, 30))`

4. Reliably find the search bar
Added additional waiting time and retries in searches.py to ensure that the search bar is found:

```
    def bingSearch(self) -> None:
        pointsBefore = self.browser.utils.getAccountPoints()
    
        rootTerm = list(self.googleTrendsShelf.keys())[0]
        terms = self.getRelatedTerms(rootTerm)
        logging.debug(f"terms={terms}")
        termsCycle: cycle[str] = cycle(terms)
        baseDelay = Searches.baseDelay
        logging.debug(f"rootTerm={rootTerm}")
    
        for i in range(self.maxRetries + 1):
            if i != 0:
                sleepTime: float
                if Searches.retriesStrategy == Searches.retriesStrategy.EXPONENTIAL:
                    sleepTime = baseDelay * 2 ** (i - 1)
                elif Searches.retriesStrategy == Searches.retriesStrategy.CONSTANT:
                    sleepTime = baseDelay
                else:
                    raise AssertionError
                logging.debug(
                    f"[BING] Search attempt not counted {i}/{Searches.maxRetries}, sleeping {sleepTime}"
                    f" seconds..."
                )
                time.sleep(sleepTime)
    
            searchbar: WebElement
            for attempt in range(5):  # Maximum of 5 attempts to find the search bar
                try:
                    searchbar = self.browser.utils.waitUntilClickable(
                        By.ID, "sb_form_q", timeToWait=50  # Increase the wait time to 50 seconds
                    )
                    searchbar.clear()
                    term = next(termsCycle)
                    logging.debug(f"term={term}")
                    time.sleep(1)
                    searchbar.send_keys(term)
                    time.sleep(1)
                    with contextlib.suppress(TimeoutException):
                        WebDriverWait(self.webdriver, 20).until(
                            expected_conditions.text_to_be_present_in_element_value(
                                (By.ID, "sb_form_q"), term
                            )
                        )
                        break
                except TimeoutException:
                    logging.warning(f"Attempt {attempt + 1}: Search bar not found. Retrying...")
                    if attempt == 4:  # If all attempts fail
                        raise TimeoutException("Failed to find the search bar after multiple attempts.")
            else:
                raise TimeoutException("Failed to find the search bar.")
    
            searchbar.submit()
    
            pointsAfter = self.browser.utils.getAccountPoints()
            if pointsBefore < pointsAfter:
                del self.googleTrendsShelf[rootTerm]
                return
    
        logging.error("[BING] Reached max search attempt retries")
    
        logging.debug("Moving passedInTerm to end of list")
        del self.googleTrendsShelf[rootTerm]
        self.googleTrendsShelf[rootTerm] = None
```

I'm leaving the issue open so that a real developer can look at it and give further input.
