### ISSUE TITLE
Issues with different keyboard layout letters

### ISSUE THREAD

**Issue by elofajnekonto** [klept0/MS-Rewards-Farmer#230]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

24a63e4

### Describe the bug

The program has issues with entering phrases containing polish letters. Screenshot attached how does it look like

### Copy and paste your error

2024-12-02 20:03:14,261 [INFO] [MORE PROMOS] Exiting
2024-12-02 20:03:14,265 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-12-02 20:03:19,455 [INFO] [BING] Remaining searches=26
2024-12-02 20:03:23,435 [DEBUG] terms=['ostrzeżenie przed mgłą']
2024-12-02 20:03:23,435 [DEBUG] rootTerm=ostrzeżenie przed mgłą
2024-12-02 20:03:23,495 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:03:45,984 [DEBUG] error send_keys
2024-12-02 20:03:46,016 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:04:08,465 [DEBUG] error send_keys
2024-12-02 20:04:08,494 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:04:30,940 [DEBUG] error send_keys
2024-12-02 20:04:30,972 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:04:53,425 [DEBUG] error send_keys
2024-12-02 20:04:53,458 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:05:15,957 [DEBUG] error send_keys
2024-12-02 20:05:15,990 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:05:38,413 [DEBUG] error send_keys
2024-12-02 20:05:38,440 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:06:00,887 [DEBUG] error send_keys
2024-12-02 20:06:00,917 [DEBUG] term=ostrzeżenie przed mgłą
2024-12-02 20:06:23,383 [DEBUG] error send_keys

### Screenshots

![image](https://github.com/user-attachments/assets/b8e2af97-5a75-425a-b993-ec23a98c0608)
![image](https://github.com/user-attachments/assets/6e6602cf-4a8d-4d9e-bd97-0afe39f25cc6)

### Value of dashboard variable

https://gist.github.com/elofajnekonto/612f745a1e933ae8a0100c9fa2b12c7f

**Comment by nicoacu** [comment]
just to confirm i have the same issue when the terms list uses a `'` (example: `mc'donalds`)  or some other similar symbol (e.g: `combinación` which is a word in spanish would also give me this error. I use `--lang en` now but still have the other problem)

**Comment by cal4** [comment]
Try develop and see if you have any luck there

**Comment by elofajnekonto** [comment]
Can't launch develop branch

ERROR:root:
Traceback (most recent call last):
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop\main.py", line 234, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop\src\browser.py", line 41, in __init__
    self.localeLang, self.localeGeo = self.getLanguageCountry(args.lang, args.geo)
                                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop\src\browser.py", line 237, in getLanguageCountry
    ).alpha_2
      ^^^^^^^
AttributeError: 'NoneType' object has no attribute 'alpha_2'

**Comment by Kyrela** [comment]
Hi @elofajnekonto, do you still have this problem with the latest version of the `develop` branch?

**Comment by elofajnekonto** [comment]
Now I'm getting this

C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2>python main.py
←[38;5;39m2025-03-31 22:02:39,082 [INFO] ********************xxxxxxxxxxx@outlook.com********************←[0m

DevTools listening on ws://127.0.0.1:50492/devtools/browser/525babb9-d76b-4ff9-81c9-f9d3aace763b
←[38;5;39m2025-03-31 22:02:52,027 [INFO] Screen size: 1773x966←[0m
←[38;5;39m2025-03-31 22:02:52,028 [INFO] Device size: 1718x815←[0m
←[38;5;39m2025-03-31 22:03:05,684 [INFO] [LOGIN] Logging-in...←[0m
←[38;5;39m2025-03-31 22:03:05,730 [INFO] [LOGIN] Entering email...←[0m
←[38;5;39m2025-03-31 22:03:16,029 [INFO] [LOGIN] Entering password...←[0m
←[38;5;39m2025-03-31 22:03:32,779 [INFO] [LOGIN] Logged-in successfully!←[0m
←[38;5;39m2025-03-31 22:03:37,289 [INFO] [POINTS] You have 0.00 points on your account←[0m
←[38;5;39m2025-03-31 22:03:37,289 [INFO] [ACTIVITIES] Trying to complete all activities...←[0m
←[38;5;196m2025-03-31 22:03:49,453 [ERROR] [ACTIVITY] Error doing Basketball drills←[0m
Traceback (most recent call last):
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2\src\activities.py", line 160, in completeActivity
    activityElement.click()
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <h3 mee-heading="heading" ng-class="{'ellipsis': !$ctrl.isDenseDashboard()}" class="c-heading ng-binding ellipsis">...</h3> is not clickable at point (561, 803). Other element would receive the click: <div id="cookieConsentContainer" class="ccanimate" nonce="" style="display: block;">...</div>
  (Session info: chrome=134.0.6998.178)
Stacktrace:
        GetHandleVerifier [0x007DC7F3+24435]
        (No symbol) [0x00762074]
        (No symbol) [0x006306E3]
        (No symbol) [0x0067EDD0]
        (No symbol) [0x0067D174]
        (No symbol) [0x0067AD17]
        (No symbol) [0x0067A001]
        (No symbol) [0x0066E685]
        (No symbol) [0x0069D7BC]
        (No symbol) [0x0066E114]
        (No symbol) [0x0069DA34]
        (No symbol) [0x006BF20A]
        (No symbol) [0x0069D5B6]
        (No symbol) [0x0066C54F]
        (No symbol) [0x0066D894]
        GetHandleVerifier [0x00AE70A3+3213347]
        GetHandleVerifier [0x00AFB0C9+3295305]
        GetHandleVerifier [0x00AF558C+3271948]
        GetHandleVerifier [0x00877360+658144]
        (No symbol) [0x0076B27D]
        (No symbol) [0x00768208]
        (No symbol) [0x007683A9]
        (No symbol) [0x0075AAC0]
        BaseThreadInitThunk [0x77615D29+25]
        RtlInitializeExceptionChain [0x77C991EB+107]
        RtlGetAppContainerNamedObjectPath [0x77C99171+561]

←[38;5;39m2025-03-31 22:04:03,558 [INFO] [COOLDOWN] Waiting for 567 seconds←[0m
←[38;5;196m2025-03-31 22:13:31,615 [ERROR] [ACTIVITY] Error doing Hollywood Icon?←[0m
Traceback (most recent call last):
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2\src\activities.py", line 160, in completeActivity
    activityElement.click()
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 94, in click
    self._execute(Command.CLICK_ELEMENT)
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webelement.py", line 395, in _execute
    return self._parent.execute(command, params)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\webdriver.py", line 380, in execute
    self.error_handler.check_response(response)
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.ElementClickInterceptedException: Message: element click intercepted: Element <h3 mee-heading="heading" ng-class="{'ellipsis': !$ctrl.isDenseDashboard()}" class="c-heading ng-binding ellipsis">...</h3> is not clickable at point (1555, 973). Other element would receive the click: <div id="cookieConsentContainer" class="ccanimate" nonce="" style="display: block;">...</div>
  (Session info: chrome=134.0.6998.178)
Stacktrace:
        GetHandleVerifier [0x007DC7F3+24435]
        (No symbol) [0x00762074]
        (No symbol) [0x006306E3]
        (No symbol) [0x0067EDD0]
        (No symbol) [0x0067D174]
        (No symbol) [0x0067AD17]
        (No symbol) [0x0067A001]
        (No symbol) [0x0066E685]
        (No symbol) [0x0069D7BC]
        (No symbol) [0x0066E114]
        (No symbol) [0x0069DA34]
        (No symbol) [0x006BF20A]
        (No symbol) [0x0069D5B6]
        (No symbol) [0x0066C54F]
        (No symbol) [0x0066D894]
        GetHandleVerifier [0x00AE70A3+3213347]
        GetHandleVerifier [0x00AFB0C9+3295305]
        GetHandleVerifier [0x00AF558C+3271948]
        GetHandleVerifier [0x00877360+658144]
        (No symbol) [0x0076B27D]
        (No symbol) [0x00768208]
        (No symbol) [0x007683A9]
        (No symbol) [0x0075AAC0]
        BaseThreadInitThunk [0x77615D29+25]
        RtlInitializeExceptionChain [0x77C991EB+107]
        RtlGetAppContainerNamedObjectPath [0x77C99171+561]

←[38;5;39m2025-03-31 22:13:41,685 [INFO] [ACTIVITIES] Done←[0m
←[38;5;39m2025-03-31 22:13:52,755 [INFO] incompleteActivities: ['Basketball drills', 'Hollywood Icon?']←[0m
←[38;5;39m2025-03-31 22:13:52,938 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...←[0m
←[38;5;39m2025-03-31 22:14:05,228 [INFO] [PUNCH CARDS] Exiting←[0m
←[38;5;39m2025-03-31 22:14:05,235 [INFO] [BING] Starting Desktop Edge Bing searches...←[0m
←[38;5;39m2025-03-31 22:14:07,438 [INFO] [BING] Remaining searches=RemainingSearches(desktop=10, mobile=0)←[0m
←[38;5;196m2025-03-31 22:14:08,329 [ERROR] ←[0m
Traceback (most recent call last):
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2\main.py", line 33, in main
    earned_points = executeBot(currentAccount)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2\main.py", line 163, in executeBot
    searches.bingSearches()
  File "C:\Users\pppppp\Desktop\MS-Rewards-Farmer-develop2\src\searches.py", line 87, in bingSearches
    trends = trends.trending_now(geo=CONFIG.browser.geolocation)[
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\site-packages\trendspy\client.py", line 575, in trending_now
    data = json.loads(data[0][2])
           ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\pppppp\AppData\Local\Programs\Python\Python311\Lib\json\__init__.py", line 339, in loads
    raise TypeError(f'the JSON object must be str, bytes or bytearray, '
TypeError: the JSON object must be str, bytes or bytearray, not NoneType
←[38;5;39m2025-03-31 22:14:08,520 [INFO] [POINTS] Data saved for the next day.←[0m

**Comment by Kyrela** [comment]
This should be reported in a separate issue then. Closing this.
