### ISSUE TITLE
The operator or administrator has refused the request (0x800710E0)

### ISSUE THREAD

**Issue by r5vx** [klept0/MS-Rewards-Farmer#234]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

 IDK what this means

### Describe the bug

After importing the file in task scheduler, i think it worked the first time (i have some points on my new account, so it worked atleast once) and then when i checked today, i got the following error: "The operator or administrator has refused the request (0x800710E0)" in task scheduler.

Just now, i tried to run it in command prompt and i got some error, which didnt seem to be happening the first time. 

### Copy and paste your error

2024-12-03 11:23:25,682 [INFO] ********************my email********************
2024-12-03 11:23:25,682 [DEBUG] in __init__
2024-12-03 11:23:26,000 [ERROR]
Traceback (most recent call last):
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\browser.py", line 48, in __init__
    ) = GenerateUserAgent().userAgent(self.browserConfig, mobile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 50, in userAgent
    app = self.getAppComponents(mobile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 116, in getAppComponents
    edgeWindowsVersion, edgeAndroidVersion = self.getEdgeVersions()
                                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 143, in getEdgeVersions
    if stableProduct := next(
                        ^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 144, in <genexpr>
    (product for product in data if product["Product"] == "Stable"),
                                    ~~~~~~~^^^^^^^^^^^
KeyError: 'Product'
2024-12-03 11:23:26,002 [WARNING] config-private.yaml doesn't exist
2024-12-03 11:23:26,002 [DEBUG] No urls found, not sending notification
2024-12-03 11:23:26,002 [INFO] ********************my 2nd email********************
2024-12-03 11:23:26,002 [DEBUG] in __init__
2024-12-03 11:23:26,270 [ERROR]
Traceback (most recent call last):
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\browser.py", line 48, in __init__
    ) = GenerateUserAgent().userAgent(self.browserConfig, mobile)
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 50, in userAgent
    app = self.getAppComponents(mobile)
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 116, in getAppComponents
    edgeWindowsVersion, edgeAndroidVersion = self.getEdgeVersions()
                                             ^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 143, in getEdgeVersions
    if stableProduct := next(
                        ^^^^^
  File "C:\Users\BlurA\Downloads\MS-Rewards-Farmer-1.1.0\MS-Rewards-Farmer-1.1.0\src\userAgentGenerator.py", line 144, in <genexpr>
    (product for product in data if product["Product"] == "Stable"),
                                    ~~~~~~~^^^^^^^^^^^
KeyError: 'Product'
2024-12-03 11:23:26,272 [WARNING] config-private.yaml doesn't exist
2024-12-03 11:23:26,272 [DEBUG] No urls found, not sending notification
2024-12-03 11:23:26,273 [INFO] [POINTS] Data saved for the next day.

### Screenshots

![image](https://github.com/user-attachments/assets/9dc304ea-c7f3-410c-a4a8-ee066277bade)


### Value of dashboard variable

https://gist.github.com/r5vx/5a0a289fb38a2edc67db5915f6efa69f

**Comment by r5vx** [comment]
Update: It seems that when I run the code manually it works (although there are some errors such as 

[35584:16632:1207/073004.324:ERROR:ssl_client_socket_impl.cc(878)] handshake failed; returned -1, SSL error code 1, net_error -202

And some other errors occuring later, but it does seem to atleast get some points. I'm not really sure how to debug this as there seem to be multiple errors occuring and I have troubleshooted quite a bit of errors already when I initially tried to get it to work. Is  there a way to fix all these errors easily?

**Comment by Kyrela** [comment]
Hi @r5vx, do you still have this problem with the latest version of the `develop` branch?
