### ISSUE TITLE
getCCodeLang function error

### ISSUE THREAD

**Issue by Ma1rwan** [klept0/MS-Rewards-Farmer#242]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

fix getCCodeLang function 

### Describe the bug

I have "fixed" the issue enough for it to not crash the script by a try statement but i hope you guys can fix the full issue bcs im still saying some bugs 

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\black2\Desktop\MS-Rewards-Farmer\main.py", line 40, in main
    earned_points = executeBot(currentAccount, args)
  File "C:\Users\black2\Desktop\MS-Rewards-Farmer\main.py", line 235, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\black2\Desktop\MS-Rewards-Farmer\src\browser.py", line 36, in __init__
    self.localeLang, self.localeGeo = self.getCCodeLang(args.lang, args.geo)
  File "C:\Users\black2\Desktop\MS-Rewards-Farmer\src\browser.py", line 206, in getCCodeLang
    nfo = ipapi.location()
  File "C:\Users\black2\AppData\Local\Programs\Python\Python310\lib\site-packages\ipapi\ipapi.py", line 83, in location
    raise AuthorizationFailed(data)

### Screenshots

llllllllllllllllll

### Value of dashboard variable

jjjlllllllllll

**Comment by cal4** [comment]
Need more detail from stack trace
