### ISSUE TITLE
Retries for each account

### ISSUE THREAD

**Issue by Guido30** [klept0/MS-Rewards-Farmer#243]
Considering how often the script can "crash" either because chrome hangs or other issues like the following (just a few examples that happened today)
```
2024-12-14 12:56:42,857 [INFO] [BING] Remaining searches=RemainingSearches(desktop=0, mobile=19)
2024-12-14 12:57:38,036 [ERROR]
Traceback (most recent call last):
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 264, in executeBot
    searches.bingSearches()
  File "C:\Repositories\MS-Rewards-Farmer\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Repositories\MS-Rewards-Farmer\src\searches.py", line 183, in bingSearch
    pointsAfter = self.browser.utils.getAccountPoints()
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\src\utils.py", line 171, in getAccountPoints
    return self.getDashboardData()["userStatus"]["availablePoints"]
           ~~~~~~~~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^
TypeError: 'NoneType' object is not subscriptable
```

```
2024-12-14 13:51:33,841 [INFO] [BING] Remaining searches=RemainingSearches(desktop=0, mobile=6)
2024-12-14 13:52:48,049 [ERROR]
Traceback (most recent call last):
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 39, in main
    earned_points = executeBot(currentAccount, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\main.py", line 264, in executeBot
    searches.bingSearches()
  File "C:\Repositories\MS-Rewards-Farmer\src\searches.py", line 136, in bingSearches
    self.bingSearch()
  File "C:\Repositories\MS-Rewards-Farmer\src\searches.py", line 172, in bingSearch
    searchbar = self.browser.utils.waitUntilClickable(
                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\src\utils.py", line 82, in waitUntilClickable
    return WebDriverWait(self.webdriver, timeToWait).until(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Repositories\MS-Rewards-Farmer\.venv\Lib\site-packages\selenium\webdriver\support\wait.py", line 105, in until
    raise TimeoutException(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException
```

Having a retry system that works for each account with a configurable option in the config.yaml like ```retries: 5``` would help a lot.
Right now its pretty annoying having to manually check if the script is still running after some time, other solutions would probably be to internally handle these errors so that the execution for that account doesnt stop and somehow can be recovered, but a faster approach might be the retry system in my opinion.

I tried using the exit code of the python process to handle retrying but the script handles the internal crashes by skipping the account, and thus always exits with a 0 code meaning success

**Comment by 28Black** [comment]
Your issues from your log file look very familiar to me. I fixed mine and posted [detailed information and code here](https://github.com/klept0/MS-Rewards-Farmer/issues/228#issuecomment-2614553829). Let me know if it solves the Timeout related crashes on your end :)

**Comment by Kyrela** [comment]
> I tried using the exit code of the python process to handle retrying but the script handles the internal crashes by skipping the account, and thus always exits with a 0 code meaning success

This is no longer the case, it exits with 1 in this case. You can also use the powershell script to automatically retry in case of an error. Does this solve your problem?

**Comment by Guido30** [comment]
Yes in one of the commits in the develop branch it was eventually fixed by using exit(1)

**Comment by Kyrela** [comment]
Nice, can I close this issue?

**Comment by Guido30** [comment]
yes
