### ISSUE TITLE
ImportError: cannot import name 'Headers' from 'h11._headers'

### ISSUE THREAD

**Issue by brendanteske** [klept0/MS-Rewards-Farmer#250]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

- [X] I've cleared the sessions folder.

### Branch

master

### Commit

50e76c6080da9ec66e9d9f06ba46122d44c18e19

### Describe the bug

I was getting the above error (in Title) and solved it via 'pip uninstall h11' then pip install 'pip install h11==0.13.0'

### Copy and paste your error

```
C:\MS-Rewards-Farmer>python main.py
Traceback (most recent call last):
  File "C:\MS-Rewards-Farmer\main.py", line 14, in <module>
    from src import (
  File "C:\MS-Rewards-Farmer\src\__init__.py", line 3, in <module>
    from .browser import Browser
  File "C:\MS-Rewards-Farmer\src\browser.py", line 9, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 14, in <module>
    from seleniumwire.webdriver import DriverCommonMixin
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\webdriver.py", line 28, in <module>
    from seleniumwire import backend, utils
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\backend.py", line 4, in <module>
    from seleniumwire.server import MitmProxy
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\server.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy import addons
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\addons\__init__.py", line 1, in <module>
    from seleniumwire.thirdparty.mitmproxy.addons import core
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\addons\core.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import command, ctx, exceptions, optmanager, platform
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\ctx.py", line 2, in <module>
    import seleniumwire.thirdparty.mitmproxy.master
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\master.py", line 7, in <module>
    from seleniumwire.thirdparty.mitmproxy import (
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\addonmanager.py", line 8, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, eventsequence, exceptions
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\eventsequence.py", line 3, in <module>
    from seleniumwire.thirdparty.mitmproxy import controller, http, tcp, websocket
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\seleniumwire\thirdparty\mitmproxy\websocket.py", line 5, in <module>
    from wsproto.frame_protocol import CloseReason, Opcode
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\wsproto\__init__.py", line 9, in <module>
    from .connection import Connection, ConnectionState, ConnectionType
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\wsproto\connection.py", line 23, in <module>
    from .utilities import LocalProtocolError
  File "C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\wsproto\utilities.py", line 12, in <module>
    from h11._headers import Headers as H11Headers
ImportError: cannot import name 'Headers' from 'h11._headers' (C:\Users\Brendan\AppData\Roaming\Python\Python310\site-packages\h11\_headers.py)
```

### Screenshots

![{37327A9E-596B-499D-BC62-67049CE99131}](https://github.com/user-attachments/assets/dda24cd1-c344-415b-a5a9-d395095ee641)

### Value of dashboard variable

N/A

**Comment by brendanteske** [comment]
Merely wanted to document this for others who may be having the same issue. I could also probably be a py newb so there's that also...
