### ISSUE TITLE
[BUG] Stopped working today

### ISSUE THREAD

**Issue by ridai260** [klept0/MS-Rewards-Farmer#27]
```
G:\scripts\MS-Rewards-Farmer>python main.py
test 9.487
Traceback (most recent call last):
  File "G:\scripts\MS-Rewards-Farmer\main.py", line 310, in <module>
    main()
  File "G:\scripts\MS-Rewards-Farmer\main.py", line 24, in main
    args = argumentParser()
  File "G:\scripts\MS-Rewards-Farmer\main.py", line 148, in argumentParser
    parser.add_argument(
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1441, in add_argument
    return self._add_action(action)
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1807, in _add_action
    self._optionals._add_action(action)
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1643, in _add_action
    action = super(_ArgumentGroup, self)._add_action(action)
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1455, in _add_action
    self._check_conflict(action)
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1592, in _check_conflict
    conflict_handler(action, confl_optionals)
  File "C:\Users\RIDAI\AppData\Local\Programs\Python\Python310\lib\argparse.py", line 1601, in _handle_conflict_error
    raise ArgumentError(action, message % conflict_string)
argparse.ArgumentError: argument -p/--pushover: conflicting option string: -p
```

Known issue? Updated python requirements and pulled latest.

**Comment by cocowalla** [comment]
@klept0 I see this was closed as "not planned" - can I please ask if that means this fork is not going to be updated any more?

**Comment by klept0** [comment]
This was a uncompleted push I did to the wrong branch - it was reverted soon after you posted this bug and there have been no issues since. I should have hit the different comment option when I was closing this out - sorry about that
