### ISSUE TITLE
[BUG] "dashboard is not defined"

### ISSUE THREAD

**Issue by Titaniumtown** [klept0/MS-Rewards-Farmer#31]
## Description
When having multiple accounts, an error occurs after/while punch cards are being completed.

## Expected Behavior
Project shouldn't crash and should run to completion.

## Actual Behavior
When doing the punch cards, the script crashes with the error "dashboard is not defined"

## Steps to Reproduce
1. Have multiple accounts in accounts.json
2. run the main.py script
3. wait for it to try and complete the punch cards

## Context
Makes the project unusable and unstable.

## Your Environment
* Version used: 4bd377f
* Environment name and version (e.g. Chrome ver): 119.0.6045.159
* Operating System and version: Fedora silverblue with an Arch Linux container

logs:
```
2023-11-21 21:30:56,313 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...
2023-11-21 21:30:56,647 [ERROR] JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=119.0.6045.159)
Stacktrace:
#0 0x5581edde25e3 <unknown>
#1 0x5581edaa50b7 <unknown>
#2 0x5581edaab2b5 <unknown>
#3 0x5581edaad9b1 <unknown>
#4 0x5581edb3671f <unknown>
#5 0x5581edb19ef2 <unknown>
#6 0x5581edb35b3d <unknown>
#7 0x5581edb19cc3 <unknown>
#8 0x5581edae50e4 <unknown>
#9 0x5581edae60ae <unknown>
#10 0x5581edda8ce1 <unknown>
#11 0x5581eddacb7e <unknown>
#12 0x5581edd964b5 <unknown>
#13 0x5581eddad7d6 <unknown>
#14 0x5581edd79dbf <unknown>
#15 0x5581eddd0748 <unknown>
#16 0x5581eddd0917 <unknown>
#17 0x5581edde1773 <unknown>
#18 0x7f84350f99eb <unknown>

Traceback (most recent call last):
  File "/var/home/primary/MS-Rewards-Farmer/main.py", line 34, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/primary/MS-Rewards-Farmer/main.py", line 200, in executeBot
    PunchCards(desktopBrowser).completePunchCards()
  File "/var/home/primary/MS-Rewards-Farmer/src/punchCards.py", line 54, in completePunchCards
    punchCards = self.browser.utils.getDashboardData()["punchCards"]
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/primary/MS-Rewards-Farmer/src/utils.py", line 144, in getDashboardData
    return self.webdriver.execute_script("return dashboard")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/primary/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/var/home/primary/.local/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/var/home/primary/.local/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=119.0.6045.159)
Stacktrace:
#0 0x5581edde25e3 <unknown>
#1 0x5581edaa50b7 <unknown>
#2 0x5581edaab2b5 <unknown>
#3 0x5581edaad9b1 <unknown>
#4 0x5581edb3671f <unknown>
#5 0x5581edb19ef2 <unknown>
#6 0x5581edb35b3d <unknown>
#7 0x5581edb19cc3 <unknown>
#8 0x5581edae50e4 <unknown>
#9 0x5581edae60ae <unknown>
#10 0x5581edda8ce1 <unknown>
#11 0x5581eddacb7e <unknown>
#12 0x5581edd964b5 <unknown>
#13 0x5581eddad7d6 <unknown>
#14 0x5581edd79dbf <unknown>
#15 0x5581eddd0748 <unknown>
#16 0x5581eddd0917 <unknown>
#17 0x5581edde1773 <unknown>
#18 0x7f84350f99eb <unknown>

2023-11-21 21:30:56,651 [INFO] [POINTS] Data saved for the next day.
```

**Comment by klept0** [comment]
Are you making sure that Chrome is not currently running on the machine? I tend to see that issue when I still have it lingering in the background of the machine

**Comment by Titaniumtown** [comment]
@klept0 I don't use chrome, I use firefox. this script is the only thing using chrome. I will restart and try again though.

**Comment by Titaniumtown** [comment]
yea, seems to work now @klept0, thanks for the tip!
