### ISSUE TITLE
[BUG] error target window already closed

### ISSUE THREAD

**Issue by Salindris** [klept0/MS-Rewards-Farmer#34]
when executing the script, it errors out with [ERROR] NoSuchWindowException: Message: no such window: target window already closed  

this happens on Ubuntu 23.04 executing the script via SSH with no other user logged on. Chrome is installed.

## Description
From the info:

2023-11-28 11:00:15,895 [INFO] ********************xxxx@xxxx.xx********************
2023-11-28 11:00:16,337 [INFO] Using default request storage
2023-11-28 11:00:16,344 [INFO] Created proxy listening on 127.0.0.1:47217
2023-11-28 11:00:16,344 [INFO] Using undetected_chromedriver
2023-11-28 11:00:17,071 [INFO] patching driver executable /home/xxxx/.local/share/undetected_chromedriver/undetected_chromedriver
2023-11-28 11:00:17,668 [INFO] Screen size: 2113x1205
2023-11-28 11:00:17,669 [INFO] Device size: 2058x1054
2023-11-28 11:00:17,735 [INFO] [LOGIN] Logging-in...
2023-11-28 11:00:23,336 [INFO] [LOGIN] Logged-in !
2023-11-28 11:00:24,481 [INFO] [LOGIN] Ensuring you are logged into Bing...
2023-11-28 11:00:31,230 [INFO] [LOGIN] Logged-in successfully !
2023-11-28 11:00:31,230 [INFO] [POINTS] You have 200.00 points on your account
2023-11-28 11:00:31,230 [INFO] [DAILY SET] Trying to complete the Daily Set...
2023-11-28 11:00:42,334 [INFO] [DAILY SET] Completing search of card 2
2023-11-28 11:00:57,198 [INFO] [DAILY SET] Completing poll of card 3
2023-11-28 11:00:58,860 [ERROR] NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=119.0.6045.159)
Stacktrace:
#0 0x557f0b9f65e3 <unknown>
#1 0x557f0b6b90b7 <unknown>
#2 0x557f0b68d1b8 <unknown>
#3 0x557f0b7336ef <unknown>
#4 0x557f0b749306 <unknown>
#5 0x557f0b72dcc3 <unknown>
#6 0x557f0b6f90e4 <unknown>
#7 0x557f0b6fa0ae <unknown>
#8 0x557f0b9bcce1 <unknown>
#9 0x557f0b9c0b7e <unknown>
#10 0x557f0b9aa4b5 <unknown>
#11 0x557f0b9c17d6 <unknown>
#12 0x557f0b98ddbf <unknown>
#13 0x557f0b9e4748 <unknown>
#14 0x557f0b9e4917 <unknown>
#15 0x557f0b9f5773 <unknown>
#16 0x7fe4a568f6ba <unknown>

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/main.py", line 34, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/main.py", line 199, in executeBot
    DailySet(desktopBrowser).completeDailySet()
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/src/dailySet.py", line 79, in completeDailySet
    self.browser.utils.resetTabs()
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/src/utils.py", line 106, in resetTabs
    self.goHome()
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/src/utils.py", line 112, in goHome
    self.webdriver.get(BASE_URL)
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/venv/lib/python3.11/site-packages/undetected_chromedriver/__init__.py", line 496, in get_wrapped
    if self.execute_script("return navigator.webdriver"):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 407, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/venv/lib/python3.11/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/opt/scripts/xxxx/MS-Rewards-Farmer/venv/lib/python3.11/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.NoSuchWindowException: Message: no such window: target window already closed
from unknown error: web view not found
  (Session info: chrome=119.0.6045.159)

## Actual Behavior
If I execute the script a second time, sometimes it gets a bit further but does never complete successfully.

## Steps to Reproduce
Executing the script with ./venv/bin/python3 main.py

## Your Environment

* Version used: current on 11/28/2023, not sure where to find a version
* Environment name and version (e.g. Chrome ver): Chrome 119.0.6045.159
* Operating System and version: Ubuntu 23.04

**Comment by klept0** [comment]
Delete your sessions folder and try again after that - I do not run it on Linux so I would have to defer to others in the chat

**Comment by klept0** [comment]
Is this still an issue or can this be closed?

**Comment by Kenneth-zh** [comment]
I encountered the problem as well, is there any solution?
