### ISSUE TITLE
[BUG] i can't do daily set

### ISSUE THREAD

**Issue by lourok01** [klept0/MS-Rewards-Farmer#35]
idk why but the bot do that since 1 week

## Description
2023-11-28 13:36:51,595 [INFO] ********************anemail@gmail.com********************
2023-11-28 13:36:53,392 [INFO] Using default request storage
2023-11-28 13:36:53,416 [INFO] Created proxy listening on 127.0.0.1:54740
2023-11-28 13:36:53,416 [INFO] Using undetected_chromedriver
2023-11-28 13:36:56,405 [INFO] patching driver executable C:\Users\hoho\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2023-11-28 13:36:57,203 [INFO] Screen size: 1595x1126
2023-11-28 13:36:57,204 [INFO] Device size: 1540x975
2023-11-28 13:36:57,283 [INFO] [LOGIN] Logging-in...
2023-11-28 13:37:01,449 [INFO] [LOGIN] Writing email...
2023-11-28 13:37:02,717 [INFO] [LOGIN] Writing password...
2023-11-28 13:39:29,701 [INFO] [LOGIN] Logged-in !
2023-11-28 13:43:48,704 [INFO] [LOGIN] Ensuring login on Bing...
2023-11-28 13:43:56,423 [INFO] [LOGIN] Logged-in successfully !
2023-11-28 13:43:56,423 [INFO] [POINTS] You have 5 650,00 points on your account
2023-11-28 13:43:56,424 [INFO] [DAILY SET] Trying to complete the Daily Set...
2023-11-28 13:48:56,773 [ERROR] TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.410
  (Session info: chrome=119.0.6045.160)
Stacktrace:
        GetHandleVerifier [0x006E72A3+45731]
        (No symbol) [0x00672D51]
        (No symbol) [0x0056880D]
        (No symbol) [0x0055ABF2]
        (No symbol) [0x0055AA9A]
        (No symbol) [0x005597F2]
        (No symbol) [0x00559FFA]
        (No symbol) [0x00563882]
        (No symbol) [0x00570BAA]
        (No symbol) [0x00573BA6]
        (No symbol) [0x0055A52C]
        (No symbol) [0x00570AC0]
        (No symbol) [0x005CB8C3]
        (No symbol) [0x005B7DD6]
        (No symbol) [0x005931F6]
        (No symbol) [0x0059439D]
        GetHandleVerifier [0x009F0716+3229462]
        GetHandleVerifier [0x00A384C8+3523784]
        GetHandleVerifier [0x00A3214C+3498316]
        GetHandleVerifier [0x00771680+611968]
        (No symbol) [0x0067CCCC]
        (No symbol) [0x00678DF8]
        (No symbol) [0x00678F1D]
        (No symbol) [0x0066B2C7]
        BaseThreadInitThunk [0x76AD7BA9+25]
        RtlInitializeExceptionChain [0x7731BD2B+107]
        RtlClearBits [0x7731BCAF+191]

Traceback (most recent call last):
  File "C:\Users\tomma\Downloads\MS-Rewards-Farmer-3.1-stable\main.py", line 32, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomma\Downloads\MS-Rewards-Farmer-3.1-stable\main.py", line 183, in executeBot
    DailySet(desktopBrowser).completeDailySet()
  File "C:\Users\tomma\Downloads\MS-Rewards-Farmer-3.1-stable\src\dailySet.py", line 18, in completeDailySet
    self.browser.utils.goHome()
  File "C:\Users\tomma\Downloads\MS-Rewards-Farmer-3.1-stable\src\utils.py", line 112, in goHome
    self.webdriver.get(BASE_URL)
  File "C:\Users\tomma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\undetected_chromedriver\__init__.py", line 629, in get_wrapped
    return orig_get(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\tomma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\undetected_chromedriver\__init__.py", line 665, in get
    return super().get(url)
           ^^^^^^^^^^^^^^^^
  File "C:\Users\tomma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 356, in get
    self.execute(Command.GET, {"url": url})
  File "C:\Users\tomma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "C:\Users\tomma\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.11_qbz5n2kfra8p0\LocalCache\local-packages\Python311\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.TimeoutException: Message: timeout: Timed out receiving message from renderer: 299.410
  (Session info: chrome=119.0.6045.160)
Stacktrace:
        GetHandleVerifier [0x006E72A3+45731]
        (No symbol) [0x00672D51]
        (No symbol) [0x0056880D]
        (No symbol) [0x0055ABF2]
        (No symbol) [0x0055AA9A]
        (No symbol) [0x005597F2]
        (No symbol) [0x00559FFA]
        (No symbol) [0x00563882]
        (No symbol) [0x00570BAA]
        (No symbol) [0x00573BA6]
        (No symbol) [0x0055A52C]
        (No symbol) [0x00570AC0]
        (No symbol) [0x005CB8C3]
        (No symbol) [0x005B7DD6]
        (No symbol) [0x005931F6]
        (No symbol) [0x0059439D]
        GetHandleVerifier [0x009F0716+3229462]
        GetHandleVerifier [0x00A384C8+3523784]
        GetHandleVerifier [0x00A3214C+3498316]
        GetHandleVerifier [0x00771680+611968]
        (No symbol) [0x0067CCCC]
        (No symbol) [0x00678DF8]
        (No symbol) [0x00678F1D]
        (No symbol) [0x0066B2C7]
        BaseThreadInitThunk [0x76AD7BA9+25]
        RtlInitializeExceptionChain [0x7731BD2B+107]
        RtlClearBits [0x7731BCAF+191]

## Expected Behavior
he should complete the daily set

## Actual Behavior
he doesn't complete the daily set

## Your Environment
* Version used:3.1
* Environment name and version (e.g. Chrome ver):119.0.6045.160 
* Operating System and version:Windows 11

**Comment by Godielvs** [comment]
same. also idk why but mine is almost always stopping at "Writing password". Most of times on the first account, but sometimes on the next account. Also happening with the original ms rewards farmer.

**Comment by klept0** [comment]
Close all instances of Chrome (use the kill script) then try it again. If that does not work then you can remove the contents of the sessions folder and then go again.

**Comment by lourok01** [comment]
> Close all instances of Chrome (use the kill script) then try it again. If that does not work then you can remove the contents of the sessions folder and then go again.

don't work and i use -v argument and the page keep loading until the bot close it

**Comment by klept0** [comment]
Pull a fresh copy of the updated files - rerun the requirements file - then report back.

**Comment by lourok01** [comment]
> Close all instances of Chrome (use the kill script) then try it again. If that does not work then you can remove the contents of the sessions folder and then go again.

ok thanks now it work but the desktop point is 90 search it's too many no ?

**Comment by klept0** [comment]
Values were adjusted for multiple things - if you see issues I would suggest looking to see what files were updated OR pull a fresh copy and try again
