### ISSUE TITLE
[BUG] [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome 

### ISSUE THREAD

**Issue by SgtSobieski** [klept0/MS-Rewards-Farmer#40]
## Actual Behavior
2023-12-02 12:40:13,498 [INFO] ********************xxx********************
2023-12-02 12:40:16,412 [INFO] Using default request storage
2023-12-02 12:40:16,471 [INFO] Created proxy listening on 127.0.0.1:39101
2023-12-02 12:40:16,472 [INFO] Using undetected_chromedriver
2023-12-02 12:40:20,859 [INFO] patching driver executable /home/xbun/.local/share/undetected_chromedriver/undetected_chromedriver
2023-12-02 12:41:21,595 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:32795
from chrome not reachable
Stacktrace:
#0 0x562c449865e3 <unknown>
#1 0x562c44648f0d <unknown>
#2 0x562c4463350a <unknown>
#3 0x562c44684cfd <unknown>
#4 0x562c4467babf <unknown>
#5 0x562c446c747f <unknown>
#6 0x562c446bdcc3 <unknown>
#7 0x562c446890e4 <unknown>
#8 0x562c4468a0ae <unknown>
#9 0x562c4494cce1 <unknown>
#10 0x562c44950b7e <unknown>
#11 0x562c4493a4b5 <unknown>
#12 0x562c449517d6 <unknown>
#13 0x562c4491ddbf <unknown>
#14 0x562c44974748 <unknown>
#15 0x562c44974917 <unknown>
#16 0x562c44985773 <unknown>
#17 0x7f4e3a694ac3 <unknown>

Traceback (most recent call last):
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/main.py", line 38, in main
    earned_points = executeBot(currentAccount, notifier, args)
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/main.py", line 201, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/src/browser.py", line 58, in __init__
    self.webdriver = self.browserSetup()
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/src/browser.py", line 97, in browserSetup
    driver = webdriver.Chrome(
  File "/home/xbun/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/xbun/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/xbun/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:32795
from chrome not reachable
Stacktrace:
#0 0x562c449865e3 <unknown>
#1 0x562c44648f0d <unknown>
#2 0x562c4463350a <unknown>
#3 0x562c44684cfd <unknown>
#4 0x562c4467babf <unknown>
#5 0x562c446c747f <unknown>
#6 0x562c446bdcc3 <unknown>
#7 0x562c446890e4 <unknown>
#8 0x562c4468a0ae <unknown>
#9 0x562c4494cce1 <unknown>
#10 0x562c44950b7e <unknown>
#11 0x562c4493a4b5 <unknown>
#12 0x562c449517d6 <unknown>
#13 0x562c4491ddbf <unknown>
#14 0x562c44974748 <unknown>
#15 0x562c44974917 <unknown>
#16 0x562c44985773 <unknown>
#17 0x7f4e3a694ac3 <unknown>

2023-12-02 12:41:21,613 [INFO] ********************xxx********************
2023-12-02 12:41:23,792 [INFO] Using default request storage
2023-12-02 12:41:23,817 [INFO] Created proxy listening on 127.0.0.1:38067
2023-12-02 12:41:23,817 [INFO] Using undetected_chromedriver
2023-12-02 12:41:26,415 [INFO] patching driver executable /home/xbun/.local/share/undetected_chromedriver/undetected_chromedriver
2023-12-02 12:42:27,086 [ERROR] WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54345
from chrome not reachable
Stacktrace:
#0 0x5556cb4565e3 <unknown>
#1 0x5556cb118f0d <unknown>
#2 0x5556cb10350a <unknown>
#3 0x5556cb154cfd <unknown>
#4 0x5556cb14babf <unknown>
#5 0x5556cb19747f <unknown>
#6 0x5556cb18dcc3 <unknown>
#7 0x5556cb1590e4 <unknown>
#8 0x5556cb15a0ae <unknown>
#9 0x5556cb41cce1 <unknown>
#10 0x5556cb420b7e <unknown>
#11 0x5556cb40a4b5 <unknown>
#12 0x5556cb4217d6 <unknown>
#13 0x5556cb3eddbf <unknown>
#14 0x5556cb444748 <unknown>
#15 0x5556cb444917 <unknown>
#16 0x5556cb455773 <unknown>
#17 0x7f35ba094ac3 <unknown>

Traceback (most recent call last):
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/main.py", line 38, in main
    earned_points = executeBot(currentAccount, notifier, args)
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/main.py", line 201, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/src/browser.py", line 58, in __init__
    self.webdriver = self.browserSetup()
  File "/home/xbun/Downloads/MS-Rewards-Farmer-master/src/browser.py", line 97, in browserSetup
    driver = webdriver.Chrome(
  File "/home/xbun/.local/lib/python3.10/site-packages/seleniumwire/undetected_chromedriver/webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "/home/xbun/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 466, in __init__
    super(Chrome, self).__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/chrome/webdriver.py", line 45, in __init__
    super().__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/chromium/webdriver.py", line 56, in __init__
    super().__init__(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 208, in __init__
    self.start_session(capabilities)
  File "/home/xbun/.local/lib/python3.10/site-packages/undetected_chromedriver/__init__.py", line 724, in start_session
    super(selenium.webdriver.chrome.webdriver.WebDriver, self).start_session(
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 292, in start_session
    response = self.execute(Command.NEW_SESSION, caps)["value"]
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/webdriver.py", line 347, in execute
    self.error_handler.check_response(response)
  File "/home/xbun/.local/lib/python3.10/site-packages/selenium/webdriver/remote/errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.WebDriverException: Message: unknown error: cannot connect to chrome at 127.0.0.1:54345
from chrome not reachable
Stacktrace:
#0 0x5556cb4565e3 <unknown>
#1 0x5556cb118f0d <unknown>
#2 0x5556cb10350a <unknown>
#3 0x5556cb154cfd <unknown>
#4 0x5556cb14babf <unknown>
#5 0x5556cb19747f <unknown>
#6 0x5556cb18dcc3 <unknown>
#7 0x5556cb1590e4 <unknown>
#8 0x5556cb15a0ae <unknown>
#9 0x5556cb41cce1 <unknown>
#10 0x5556cb420b7e <unknown>
#11 0x5556cb40a4b5 <unknown>
#12 0x5556cb4217d6 <unknown>
#13 0x5556cb3eddbf <unknown>
#14 0x5556cb444748 <unknown>
#15 0x5556cb444917 <unknown>
#16 0x5556cb455773 <unknown>
#17 0x7f35ba094ac3 <unknown>

* Operating System and version: Xubuntu on a virtual machine

**Comment by klept0** [comment]
Is this still an issue or can this be closed?

**Comment by SgtSobieski** [comment]
Yes it is. I only get it on Ubuntu. Dont know if anyone else uses it that way and if there is something to consider...

**Comment by vicrg33** [comment]
I get the same error on Windows. I think that it only happens when Chrome is updated. 

There is a workaround that is to remove the sessions folders... However, that forces to log-in again manually (I have 2FA) so, is there any other solution for this?

**Comment by SgtSobieski** [comment]
Seems to be the same like this one:
https://github.com/klept0/MS-Rewards-Farmer/issues/10
