### ISSUE TITLE
[BUG] dashboard is not defined

### ISSUE THREAD

**Issue by lourok01** [klept0/MS-Rewards-Farmer#61]
dashboard is not defined

## Description
 after the versus game failed i get this error " dashboard is not defined" 

## Expected Behavior
 continue working

## Actual Behavior
 2024-01-05 14:40:45,966 [INFO] Using default request storage
2024-01-05 14:40:45,975 [INFO] Created proxy listening on 127.0.0.1:51798
2024-01-05 14:40:45,975 [INFO] Using undetected_chromedriver
2024-01-05 14:40:47,012 [INFO] patching driver executable C:\Users\Utilisateur\appdata\roaming\undetected_chromedriver\undetected_chromedriver.exe
2024-01-05 14:40:48,121 [INFO] Screen size: 1083x949
2024-01-05 14:40:48,122 [INFO] Device size: 1028x798
2024-01-05 14:40:48,156 [INFO] [LOGIN] Logging-in...
2024-01-05 14:40:57,937 [INFO] [LOGIN] Logged-in !
2024-01-05 14:40:59,340 [INFO] [LOGIN] Ensuring you are logged into Bing...
2024-01-05 14:41:04,273 [INFO] [LOGIN] Logged-in successfully !
2024-01-05 14:41:04,273 [INFO] [POINTS] You have 20 950,00 points on your account
2024-01-05 14:41:04,275 [INFO] [DAILY SET] Trying to complete the Daily Set...
2024-01-05 14:41:05,739 [INFO] [DAILY SET] Completed the Daily Set successfully !
2024-01-05 14:41:05,740 [INFO] [PUNCH CARDS] Trying to complete the Punch Cards...
2024-01-05 14:41:05,800 [INFO] [PUNCH CARDS] Completed the Punch Cards successfully !
2024-01-05 14:41:15,547 [INFO] [MORE PROMOS] Trying to complete More Promotions...
2024-01-05 14:41:16,898 [INFO] [MORE PROMOS] Completed More Promotions successfully !
2024-01-05 14:42:04,466 [INFO] [VERSUS GAME] Versus Game Failed!
2024-01-05 14:42:05,094 [ERROR] JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=120.0.6099.200)
Stacktrace:
	GetHandleVerifier [0x00D06EE3+174339]
	(No symbol) [0x00C30A51]
	(No symbol) [0x00946FF6]
	(No symbol) [0x0094AEAC]
	(No symbol) [0x0094C7C1]
	(No symbol) [0x009AACD8]
	(No symbol) [0x0099700C]
	(No symbol) [0x009AA104]
	(No symbol) [0x00996DA6]
	(No symbol) [0x00971034]
	(No symbol) [0x00971F8D]
	GetHandleVerifier [0x00DA4B1C+820540]
	sqlite3_dbdata_init [0x00E653EE+653550]
	sqlite3_dbdata_init [0x00E64E09+652041]
	sqlite3_dbdata_init [0x00E597CC+605388]
	sqlite3_dbdata_init [0x00E65D9B+656027]
	(No symbol) [0x00C3FE6C]
	(No symbol) [0x00C383B8]
	(No symbol) [0x00C384DD]
	(No symbol) [0x00C25818]
	BaseThreadInitThunk [0x75B27BA9+25]
	RtlInitializeExceptionChain [0x7708BD2B+107]
	RtlClearBits [0x7708BCAF+191]
Traceback (most recent call last):
  File "C:\Users\Utilisateur\Downloads\MS-Rewards-Farmer-master\main.py", line 47, in main
    earned_points = executeBot(currentAccount, notifier, args)
                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\Downloads\MS-Rewards-Farmer-master\main.py", line 240, in executeBot
    ) = desktopBrowser.utils.getRemainingSearches()
        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\Downloads\MS-Rewards-Farmer-master\src\utils.py", line 255, in getRemainingSearches
    dashboard = self.getDashboardData()
                ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\Downloads\MS-Rewards-Farmer-master\src\utils.py", line 154, in getDashboardData
    return self.webdriver.execute_script("return dashboard")
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 408, in execute_script
    return self.execute(command, {"script": script, "args": converted_args})["value"]
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Utilisateur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\webdriver.py", line 348, in execute
    self.error_handler.check_response(response)
  File "C:\Users\Utilisateur\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.12_qbz5n2kfra8p0\LocalCache\local-packages\Python312\site-packages\selenium\webdriver\remote\errorhandler.py", line 229, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.JavascriptException: Message: javascript error: dashboard is not defined
  (Session info: chrome=120.0.6099.200)
Stacktrace:
	GetHandleVerifier [0x00D06EE3+174339]
	(No symbol) [0x00C30A51]
	(No symbol) [0x00946FF6]
	(No symbol) [0x0094AEAC]
	(No symbol) [0x0094C7C1]
	(No symbol) [0x009AACD8]
	(No symbol) [0x0099700C]
	(No symbol) [0x009AA104]
	(No symbol) [0x00996DA6]
	(No symbol) [0x00971034]
	(No symbol) [0x00971F8D]
	GetHandleVerifier [0x00DA4B1C+820540]
	sqlite3_dbdata_init [0x00E653EE+653550]
	sqlite3_dbdata_init [0x00E64E09+652041]
	sqlite3_dbdata_init [0x00E597CC+605388]
	sqlite3_dbdata_init [0x00E65D9B+656027]
	(No symbol) [0x00C3FE6C]
	(No symbol) [0x00C383B8]
	(No symbol) [0x00C384DD]
	(No symbol) [0x00C25818]
	BaseThreadInitThunk [0x75B27BA9+25]
	RtlInitializeExceptionChain [0x7708BD2B+107]
	RtlClearBits [0x7708BCAF+191]

2024-01-05 14:42:05,099 [INFO] [POINTS] Data saved for the next day.

## Your Environment
* chrome 120.0.6099.200
* Window 11
* i use only one account

**Comment by klept0** [comment]
You can test wait times on the versus game for your connection - there is not a one time fits all for this situation

**Comment by TimNick151297** [comment]
Any way to exclude versus game all together?

**Comment by Titaniumtown** [comment]
> Any way to exclude versus game all together?

I've personally simply edited the main.py in order to do that

**Comment by klept0** [comment]
This is not really a bug per se - this happens when your connection/instance does not load the versusgame so it throws an error. You can either comment out the `VersusGame(desktopBrowser).completeVersusGame()` from the main.py file OR try to increase the wait times in the versus.py script for your connection/load times.

**Comment by klept0** [comment]
Closing as versus has been disabled - pull updated copy of files and issue should no longer occur
