### ISSUE TITLE
[BUG]  chromedriver and chromium v121 on Debian is flawed 

### ISSUE THREAD

**Issue by icescoop12** [klept0/MS-Rewards-Farmer#71]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Been running the bot on chromium ,on a raspberry pi with hardly any issues in the past
But recently with newer versions of chromium and its web security lately
Running in headless mode I’m seeing the images and cookies blocked on http sites bing ect,
Which i really think is causing issues of the bot hanging
All the time
I’ve tried adding the argument —disable-web-security 
To browser.py along with -user-dater-dir=/home/******/temp
But seems to still run with standard security ,as I’m trying to turn it off,tried turning it off in settings as it runs in headless mode but doesn’t alter anything and still http sites cookies and images are blocked
can anyone assist
Tried to downgrade chromium with the matching chromedriver but seems to be impossible on Debian looked everywhere 
If anyone can point me on how to get chromium downgraded with a matching chromedriver on raspberry pi if there’s no solution to turning off security on the latest chromium
Thanks

### Copy and paste your error

As described 

### Screenshots

Later

### Value of dashboard variable

Na

**Comment by icescoop12** [comment]
think its this bot as older version of rewards farmer doesnt have the block images problem when in headless
can you please look into it klept0

**Comment by redgfws** [comment]
2024-02-16 00:51:10,577 [ERROR] TypeError: '<' not supported between instances of 'NoneType' and 'int'
Traceback (most recent call last):
  File "C:\Users\ankit\Downloads\MS-Rewards-Farmer-master\MS-Rewards-Farmer-master\main.py", line 47, in main
    earned_points = executeBot(currentAccount, notifier, args)
  File "C:\Users\ankit\Downloads\MS-Rewards-Farmer-master\MS-Rewards-Farmer-master\main.py", line 221, in executeBot
    with Browser(mobile=False, account=currentAccount, args=args) as desktopBrowser:
  File "C:\Users\ankit\Downloads\MS-Rewards-Farmer-master\MS-Rewards-Farmer-master\src\browser.py", line 41, in __init__
    self.webdriver = self.browserSetup()
  File "C:\Users\ankit\Downloads\MS-Rewards-Farmer-master\MS-Rewards-Farmer-master\src\browser.py", line 86, in browserSetup
    driver = webdriver.Chrome(
  File "C:\Users\ankit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 61, in __init__
    super().__init__(*args, **kwargs)
  File "C:\Users\ankit\AppData\Local\Packages\PythonSoftwareFoundation.Python.3.10_qbz5n2kfra8p0\LocalCache\local-packages\Python310\site-packages\undetected_chromedriver\__init__.py", line 386, in __init__
    if self.patcher.version_main < 108:
TypeError: '<' not supported between instances of 'NoneType' and 'int'
