### ISSUE TITLE
[ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)

### ISSUE THREAD

**Issue by RobertMochnacky** [klept0/MS-Rewards-Farmer#84]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

Dear,
After making the farmer working with my MS account it stopped suddenly with the error pasted in the error field. I cannot make it work again. I did no changes on the system except that I have tried to use different account.json for another account as I wanted to avoid using my primary MS account used for a lot more than just collecting rewards points. Neither of the accounts work now.
Can some help and point to the right direction?

### Copy and paste your error

2024-03-04 20:06:55,463 [INFO] [BING] Starting Desktop Edge Bing searches...
2024-03-04 20:06:55,860 [ERROR] JSONDecodeError: Expecting value: line 1 column 1 (char 0)
Traceback (most recent call last):
  File "/home/roboadm/MS-Rewards-Farmer/main.py", line 47, in main
    earned_points = executeBot(currentAccount, notifier, args)
  File "/home/roboadm/MS-Rewards-Farmer/main.py", line 249, in executeBot
    accountPointsCounter = Searches(desktopBrowser).bingSearches(
  File "/home/roboadm/MS-Rewards-Farmer/src/searches.py", line 61, in bingSearches
    search_terms = self.getGoogleTrends(numberOfSearches)
  File "/home/roboadm/MS-Rewards-Farmer/src/searches.py", line 31, in getGoogleTrends
    trends = json.loads(r.text[6:])
  File "/usr/lib/python3.10/json/__init__.py", line 346, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.10/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.10/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
2024-03-04 20:06:55,874 [INFO] [POINTS] Data saved for the next day.

### Screenshots

![Screenshot 2024-03-04 201001](https://github.com/klept0/MS-Rewards-Farmer/assets/65652833/7e74938e-c02c-4c18-85c5-cc1c3b5bd153)

### Value of dashboard variable

https://gist.github.com/RobertMochnacky/fc18120fb60397a043f03abba27c2045#file-gistfile1-txt

**Comment by klept0** [comment]
1. What OS?
2. What flags are you using?
3. Is this a recent copy of the files on the repo?

**Comment by RobertMochnacky** [comment]
Good evening,

sorry for the late reply...

Ubuntu OS
It does not work without a flag, although if I use --geo US for example (I'm in Europe btw) it works. This is my last observation and outcome of the testing. Does geo US flag have any implications like a possibility for a ban/account blocking?
Yes, I have the recent copy of the files from repo.
~/MS-Rewards-Farmer$ git status
On branch master
Your branch is up to date with 'origin/master'.

Thank you in advance.
