### ISSUE TITLE
[BUG] Error caused by blinker version

### ISSUE THREAD

**Issue by OmegaBlurz** [klept0/MS-Rewards-Farmer#95]
### Before submitting a bug report...

- [X] This bug wasn't already reported.
(I have checked every bug report on GitHub)

### Title

- [X] The title is no longer "[BUG] Title" and I edited it with the right error name.

### Describe the bug

When running the script with blinker version 1.8.0 or newer the script crashes, resolved it by reinstalling version 1.7.0. Would like to know if it was just me having this happen.

### Copy and paste your error

Traceback (most recent call last):
  File "C:\Users\{USER}\Documents\MS-Rewards-Farmer\main.py", line 18, in <module>
    from src import (
  File "C:\Users\{USER}\Documents\MS-Rewards-Farmer\src\__init__.py", line 1, in <module>
    from .browser import Browser
  File "C:\Users\{USER}\Documents\MS-Rewards-Farmer\src\browser.py", line 8, in <module>
    import seleniumwire.undetected_chromedriver as webdriver
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\__init__.py", line 1, in <module>
    from .webdriver import Chrome, ChromeOptions
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\undetected_chromedriver\webdriver.py", line 12, in <module>
    from seleniumwire.inspect import InspectRequestsMixin
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\inspect.py", line 7, in <module>
    from seleniumwire import har
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\har.py", line 11, in <module>
    from seleniumwire.thirdparty.mitmproxy import connections
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\connections.py", line 10, in <module>
    from seleniumwire.thirdparty.mitmproxy.net import tls, tcp
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\net\tls.py", line 15, in <module>
    import seleniumwire.thirdparty.mitmproxy.options
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\options.py", line 5, in <module>
    from seleniumwire.thirdparty.mitmproxy import optmanager
  File "C:\Users\{USER}\AppData\Local\Programs\Python\Python312\Lib\site-packages\seleniumwire\thirdparty\mitmproxy\optmanager.py", line 9, in <module>
    import blinker._saferef
ModuleNotFoundError: No module named 'blinker._saferef'

### Screenshots

-

### Value of dashboard variable

-

**Comment by Wpnnt** [comment]
same here
